import { mutation } from "./_generated/server";

export const clearDatabase = mutation({
  handler: async (ctx) => {
    // Clear all tables in order (respecting foreign key-like relationships)
    const recommendations = await ctx.db.query("recommendations").collect();
    for (const rec of recommendations) {
      await ctx.db.delete(rec._id);
    }
    
    const pricingTiers = await ctx.db.query("pricingTiers").collect();
    for (const tier of pricingTiers) {
      await ctx.db.delete(tier._id);
    }
    
    const tools = await ctx.db.query("tools").collect();
    for (const tool of tools) {
      await ctx.db.delete(tool._id);
    }
    
    const categories = await ctx.db.query("categories").collect();
    for (const cat of categories) {
      await ctx.db.delete(cat._id);
    }
    
    const projects = await ctx.db.query("projects").collect();
    for (const proj of projects) {
      await ctx.db.delete(proj._id);
    }
    
    return { message: "Database cleared successfully" };
  },
});

export const seedDatabase = mutation({
  handler: async (ctx) => {
    // Check if already seeded
    const existingCategories = await ctx.db.query("categories").collect();
    if (existingCategories.length > 0) {
      return { message: "Database already seeded" };
    }

    // Seed categories - comprehensive list from TECH_STACK_DATABASE
    const categories = [
      { name: "IDEs & Editors", slug: "ides", description: "Code editors and development environments", icon: "💻", sortOrder: 1 },
      { name: "AI Assistants", slug: "ai-assistants", description: "AI-powered coding assistants", icon: "🤖", sortOrder: 2 },
      { name: "Frontend", slug: "frontend", description: "Frontend frameworks and libraries", icon: "⚛️", sortOrder: 3 },
      { name: "Meta-Frameworks", slug: "meta-frameworks", description: "Full-stack frameworks", icon: "🏗️", sortOrder: 4 },
      { name: "Backend", slug: "backend", description: "Backend runtimes and frameworks", icon: "🔧", sortOrder: 5 },
      { name: "Databases", slug: "databases", description: "Database platforms and services", icon: "🗄️", sortOrder: 6 },
      { name: "Auth", slug: "auth", description: "Authentication providers", icon: "🔐", sortOrder: 7 },
      { name: "Hosting", slug: "hosting", description: "Hosting and deployment platforms", icon: "☁️", sortOrder: 8 },
      { name: "Realtime", slug: "realtime", description: "Realtime and WebSocket services", icon: "⚡", sortOrder: 9 },
      { name: "LLMs", slug: "llms", description: "Large Language Models and AI APIs", icon: "🧠", sortOrder: 10 },
      { name: "Styling", slug: "styling", description: "CSS frameworks and component libraries", icon: "🎨", sortOrder: 11 },
      { name: "Testing", slug: "testing", description: "Testing frameworks and tools", icon: "🧪", sortOrder: 12 },
      { name: "Observability", slug: "observability", description: "Error tracking, analytics, and monitoring", icon: "📊", sortOrder: 13 },
      { name: "Vibe Coding", slug: "vibe-coding", description: "AI-powered app builders and browser-based development tools", icon: "✨", sortOrder: 14 },
      { name: "CLI Agents", slug: "cli-agents", description: "Command-line AI coding agents and assistants", icon: "⌨️", sortOrder: 15 },
    ];

    const categoryIds: Record<string, any> = {};
    for (const cat of categories) {
      const id = await ctx.db.insert("categories", cat);
      categoryIds[cat.slug] = id;
    }

    // Seed tools
    const tools = [
      // IDEs
      {
        name: "VS Code",
        slug: "vscode",
        tagline: "Code editing. Redefined.",
        description: "Free, open-source code editor with extensive extension marketplace",
        websiteUrl: "https://code.visualstudio.com",
        githubUrl: "https://github.com/microsoft/vscode",
        categoryId: categoryIds["ides"],
        pricingModel: "free" as const,
        githubStars: 165000,
        pros: ["Massive extension ecosystem", "Free & open source", "Great Git integration"],
        cons: ["Can be resource heavy", "Electron-based"],
        bestFor: ["General development", "Web development", "Extension lovers"],
        features: ["IntelliSense", "Debugging", "Git integration", "Extensions"],
        tags: ["editor", "free", "microsoft", "extensions"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Cursor",
        slug: "cursor",
        tagline: "The AI-first code editor",
        description: "AI-native IDE built on VS Code with deep AI integration",
        websiteUrl: "https://cursor.sh",
        categoryId: categoryIds["ides"],
        pricingModel: "freemium" as const,
        pros: ["Best AI integration", "VS Code familiar", "Multi-file editing"],
        cons: ["Subscription required", "Closed source"],
        bestFor: ["AI-assisted coding", "Rapid prototyping", "Complex refactoring"],
        features: ["AI Chat", "Composer", "Agent Mode", "Codebase awareness"],
        tags: ["ai", "editor", "vscode-fork", "premium"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Windsurf",
        slug: "windsurf",
        tagline: "Agentic IDE by Codeium",
        description: "AI-powered IDE with autonomous coding capabilities",
        websiteUrl: "https://codeium.com/windsurf",
        categoryId: categoryIds["ides"],
        pricingModel: "freemium" as const,
        pros: ["Autonomous coding", "Lower price than Cursor", "Good context"],
        cons: ["Newer platform", "Smaller community"],
        bestFor: ["Autonomous code generation", "Budget AI coding"],
        features: ["Cascade AI", "Flow actions", "Context awareness"],
        tags: ["ai", "editor", "codeium", "autonomous"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Zed",
        slug: "zed",
        tagline: "Code at the speed of thought",
        description: "High-performance, multiplayer code editor built in Rust",
        websiteUrl: "https://zed.dev",
        githubUrl: "https://github.com/zed-industries/zed",
        categoryId: categoryIds["ides"],
        pricingModel: "free" as const,
        githubStars: 50000,
        pros: ["Extremely fast", "Native collaboration", "Rust-based"],
        cons: ["Fewer extensions", "No Windows yet"],
        bestFor: ["Speed enthusiasts", "Pair programming", "Minimalists"],
        features: ["GPU rendering", "Multiplayer", "AI integration", "Vim mode"],
        tags: ["fast", "rust", "collaboration", "free"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "JetBrains IDEs",
        slug: "jetbrains",
        tagline: "Professional IDEs for every language",
        description: "Full IDE suite with deep language support and powerful refactoring",
        websiteUrl: "https://www.jetbrains.com",
        categoryId: categoryIds["ides"],
        pricingModel: "freemium" as const,
        pros: ["Best-in-class for specific languages", "Powerful refactoring", "Deep language support"],
        cons: ["Resource heavy", "Expensive", "Slower startup"],
        bestFor: ["Enterprise development", "Language-specific tooling", "Heavy refactoring"],
        features: ["Deep language support", "Refactoring", "Debugging", "JetBrains AI Assistant"],
        tags: ["ide", "enterprise", "java", "kotlin", "python"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Neovim",
        slug: "neovim",
        tagline: "Hyperextensible Vim-based text editor",
        description: "Terminal editor with Lua configuration and LSP support",
        websiteUrl: "https://neovim.io",
        githubUrl: "https://github.com/neovim/neovim",
        categoryId: categoryIds["ides"],
        pricingModel: "free" as const,
        githubStars: 85000,
        pros: ["Extremely fast", "Infinitely customizable", "Lightweight"],
        cons: ["Steep learning curve", "Requires configuration"],
        bestFor: ["Power users", "Terminal workflows", "Customization enthusiasts"],
        features: ["Lua configuration", "LSP support", "Modal editing", "Plugin ecosystem"],
        tags: ["terminal", "vim", "lua", "lightweight"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      // AI Assistants
      {
        name: "GitHub Copilot",
        slug: "github-copilot",
        tagline: "Your AI pair programmer",
        description: "AI coding assistant integrated into your IDE",
        websiteUrl: "https://github.com/features/copilot",
        categoryId: categoryIds["ai-assistants"],
        pricingModel: "paid" as const,
        pros: ["Wide IDE support", "Reliable", "Good for boilerplate"],
        cons: ["Less context than competitors", "Basic chat"],
        bestFor: ["General coding", "Boilerplate generation", "IDE integration"],
        features: ["Inline suggestions", "Chat", "Workspace awareness"],
        tags: ["ai", "github", "microsoft", "coding"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Claude",
        slug: "claude",
        tagline: "AI assistant by Anthropic",
        description: "Advanced AI for coding, analysis, and complex reasoning",
        websiteUrl: "https://claude.ai",
        categoryId: categoryIds["ai-assistants"],
        pricingModel: "freemium" as const,
        pros: ["Best coding accuracy", "Long context (200K)", "Trustworthy"],
        cons: ["No memory in free tier", "Can be conservative"],
        bestFor: ["Complex coding", "Code review", "Long codebases"],
        features: ["Artifacts", "Projects", "Computer use", "200K context"],
        tags: ["ai", "anthropic", "coding", "reasoning"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "GPT-4 / ChatGPT",
        slug: "chatgpt",
        tagline: "AI assistant by OpenAI",
        description: "Versatile AI with largest ecosystem and polished UX",
        websiteUrl: "https://chat.openai.com",
        categoryId: categoryIds["ai-assistants"],
        pricingModel: "freemium" as const,
        pros: ["Largest ecosystem", "Most polished UX", "Versatile"],
        cons: ["Can be lazy on complex tasks", "Expensive API"],
        bestFor: ["General assistance", "Ecosystem integration", "Custom GPTs"],
        features: ["Memory", "Custom GPTs", "Canvas", "Plugins", "128K context"],
        tags: ["ai", "openai", "gpt", "popular"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Gemini",
        slug: "gemini",
        tagline: "Google's multimodal AI",
        description: "Multimodal AI with 2M token context and Google integration",
        websiteUrl: "https://gemini.google.com",
        categoryId: categoryIds["ai-assistants"],
        pricingModel: "freemium" as const,
        pros: ["Largest context window (2M)", "Good reasoning", "Free tier"],
        cons: ["Inconsistent quality", "Overly cautious"],
        bestFor: ["Multimodal tasks", "Google ecosystem", "Long context"],
        features: ["2M context", "Multimodal", "Google integration"],
        tags: ["ai", "google", "multimodal", "long-context"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Cody",
        slug: "cody",
        tagline: "AI coding assistant by Sourcegraph",
        description: "AI assistant with codebase-wide context and code search",
        websiteUrl: "https://sourcegraph.com/cody",
        categoryId: categoryIds["ai-assistants"],
        pricingModel: "freemium" as const,
        pros: ["Best for large codebases", "Enterprise features", "Multi-repo support"],
        cons: ["Requires Sourcegraph for full power"],
        bestFor: ["Large codebases", "Enterprise", "Code search"],
        features: ["Codebase-wide context", "Code search", "Multi-repo"],
        tags: ["ai", "sourcegraph", "enterprise", "code-search"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Supermaven",
        slug: "supermaven",
        tagline: "Fastest AI autocomplete",
        description: "AI autocomplete with 300K token context and instant suggestions",
        websiteUrl: "https://supermaven.com",
        categoryId: categoryIds["ai-assistants"],
        pricingModel: "freemium" as const,
        pros: ["Fastest autocomplete", "Large context (300K)", "Low latency"],
        cons: ["Less capable for complex reasoning"],
        bestFor: ["Fast autocomplete", "Low latency", "Speed-focused"],
        features: ["300K token context", "Instant suggestions", "IDE integration"],
        tags: ["ai", "autocomplete", "fast", "low-latency"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      // Frontend
      {
        name: "React",
        slug: "react",
        tagline: "The library for web and native UIs",
        description: "JavaScript library for building user interfaces",
        websiteUrl: "https://react.dev",
        githubUrl: "https://github.com/facebook/react",
        categoryId: categoryIds["frontend"],
        pricingModel: "free" as const,
        githubStars: 230000,
        pros: ["Massive ecosystem", "Job market", "Flexibility"],
        cons: ["Boilerplate", "Decision fatigue"],
        bestFor: ["Complex UIs", "Large teams", "Ecosystem needs"],
        features: ["Components", "Hooks", "Concurrent rendering", "Server Components"],
        tags: ["ui", "javascript", "meta", "popular"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Vue.js",
        slug: "vuejs",
        tagline: "The Progressive JavaScript Framework",
        description: "Approachable, performant and versatile framework",
        websiteUrl: "https://vuejs.org",
        githubUrl: "https://github.com/vuejs/vue",
        categoryId: categoryIds["frontend"],
        pricingModel: "free" as const,
        githubStars: 208000,
        pros: ["Great DX", "Gentle learning curve", "Good docs"],
        cons: ["Smaller ecosystem", "Fewer jobs"],
        bestFor: ["Progressive enhancement", "Beginners", "SFCs"],
        features: ["Composition API", "SFC", "Reactivity", "Transitions"],
        tags: ["ui", "javascript", "progressive", "beginner-friendly"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Svelte",
        slug: "svelte",
        tagline: "Cybernetically enhanced web apps",
        description: "Compiler that generates minimal JavaScript",
        websiteUrl: "https://svelte.dev",
        githubUrl: "https://github.com/sveltejs/svelte",
        categoryId: categoryIds["frontend"],
        pricingModel: "free" as const,
        githubStars: 80000,
        pros: ["Smallest bundles", "Best DX", "Intuitive syntax"],
        cons: ["Smaller ecosystem", "Fewer jobs"],
        bestFor: ["Performance-critical apps", "Small bundles", "Simplicity"],
        features: ["No virtual DOM", "Compile-time", "Runes", "Transitions"],
        tags: ["ui", "compiler", "performance", "simple"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Angular",
        slug: "angular",
        tagline: "The web development framework for building the future",
        description: "Full framework with batteries-included approach for enterprise apps",
        websiteUrl: "https://angular.dev",
        githubUrl: "https://github.com/angular/angular",
        categoryId: categoryIds["frontend"],
        pricingModel: "free" as const,
        githubStars: 96000,
        pros: ["Batteries-included", "Enterprise-ready", "Consistent"],
        cons: ["Steep learning curve", "Verbose", "Slower adoption"],
        bestFor: ["Enterprise apps", "Large teams", "TypeScript-first"],
        features: ["Signals", "Dependency injection", "CLI", "RxJS"],
        tags: ["ui", "enterprise", "typescript", "google"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Solid.js",
        slug: "solidjs",
        tagline: "Simple and performant reactivity",
        description: "Reactive framework with fine-grained reactivity and no virtual DOM",
        websiteUrl: "https://www.solidjs.com",
        githubUrl: "https://github.com/solidjs/solid",
        categoryId: categoryIds["frontend"],
        pricingModel: "free" as const,
        githubStars: 33000,
        pros: ["Fastest benchmarks", "React-like DX", "Small bundle"],
        cons: ["Small ecosystem", "Fewer resources"],
        bestFor: ["Performance-critical apps", "React-like DX", "Fine-grained reactivity"],
        features: ["Fine-grained reactivity", "No virtual DOM", "JSX", "Signals"],
        tags: ["ui", "performance", "reactive", "jsx"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      // Meta-Frameworks
      {
        name: "Next.js",
        slug: "nextjs",
        tagline: "The React Framework for the Web",
        description: "Full-stack React framework with SSR, SSG, and more",
        websiteUrl: "https://nextjs.org",
        githubUrl: "https://github.com/vercel/next.js",
        categoryId: categoryIds["meta-frameworks"],
        pricingModel: "free" as const,
        githubStars: 128000,
        pros: ["Most mature", "Best ecosystem", "Vercel integration"],
        cons: ["Complexity", "Vercel lock-in concerns"],
        bestFor: ["Production React apps", "Full-stack", "SSR/SSG"],
        features: ["App Router", "Server Components", "API Routes", "ISR"],
        tags: ["react", "fullstack", "vercel", "ssr"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Nuxt",
        slug: "nuxt",
        tagline: "The Intuitive Vue Framework",
        description: "Full-stack Vue framework with great DX",
        websiteUrl: "https://nuxt.com",
        githubUrl: "https://github.com/nuxt/nuxt",
        categoryId: categoryIds["meta-frameworks"],
        pricingModel: "free" as const,
        githubStars: 55000,
        pros: ["Great DX", "Flexible deployment", "Good modules"],
        cons: ["Smaller than Next.js"],
        bestFor: ["Vue production apps", "SSR/SSG", "Modules"],
        features: ["Nitro engine", "Auto-imports", "Modules", "Hybrid rendering"],
        tags: ["vue", "fullstack", "nitro", "ssr"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "SvelteKit",
        slug: "sveltekit",
        tagline: "Web development, streamlined",
        description: "Full-stack Svelte framework",
        websiteUrl: "https://kit.svelte.dev",
        githubUrl: "https://github.com/sveltejs/kit",
        categoryId: categoryIds["meta-frameworks"],
        pricingModel: "free" as const,
        githubStars: 19000,
        pros: ["Excellent DX", "Flexible", "Small bundles"],
        cons: ["Smaller ecosystem"],
        bestFor: ["Svelte apps", "Performance-focused"],
        features: ["File routing", "Adapters", "Form actions", "Load functions"],
        tags: ["svelte", "fullstack", "adapters", "ssr"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Astro",
        slug: "astro",
        tagline: "The web framework for content-driven websites",
        description: "Framework-agnostic with islands architecture and zero JS by default",
        websiteUrl: "https://astro.build",
        githubUrl: "https://github.com/withastro/astro",
        categoryId: categoryIds["meta-frameworks"],
        pricingModel: "free" as const,
        githubStars: 48000,
        pros: ["Best for content sites", "Use any framework", "Fast"],
        cons: ["Not for highly interactive apps"],
        bestFor: ["Content sites", "Blogs", "Marketing pages"],
        features: ["Islands architecture", "Zero JS by default", "Any framework", "SSG/SSR"],
        tags: ["content", "islands", "performance", "static"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Remix",
        slug: "remix",
        tagline: "Build Better Websites",
        description: "Full-stack React framework focused on web standards",
        websiteUrl: "https://remix.run",
        githubUrl: "https://github.com/remix-run/remix",
        categoryId: categoryIds["meta-frameworks"],
        pricingModel: "free" as const,
        githubStars: 30000,
        pros: ["Web standards focus", "Great UX patterns", "Progressive enhancement"],
        cons: ["Smaller than Next.js", "Shopify acquisition uncertainty"],
        bestFor: ["Web standards", "Progressive enhancement", "Forms"],
        features: ["Nested routing", "Loaders/Actions", "Web Fetch API", "Error boundaries"],
        tags: ["react", "web-standards", "shopify", "forms"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      // Backend Runtimes
      {
        name: "Node.js",
        slug: "nodejs",
        tagline: "JavaScript runtime built on Chrome's V8",
        description: "Server-side JavaScript runtime with massive ecosystem",
        websiteUrl: "https://nodejs.org",
        githubUrl: "https://github.com/nodejs/node",
        categoryId: categoryIds["backend"],
        pricingModel: "free" as const,
        githubStars: 108000,
        pros: ["Massive ecosystem", "Large hiring pool", "Stability"],
        cons: ["Single-threaded", "Callback complexity"],
        bestFor: ["General web development", "Large ecosystem needs", "npm packages"],
        features: ["npm ecosystem", "Async I/O", "Mature tooling", "V8 engine"],
        tags: ["javascript", "runtime", "npm", "server"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Bun",
        slug: "bun",
        tagline: "Incredibly fast JavaScript runtime",
        description: "All-in-one JavaScript runtime with built-in bundler and package manager",
        websiteUrl: "https://bun.sh",
        githubUrl: "https://github.com/oven-sh/bun",
        categoryId: categoryIds["backend"],
        pricingModel: "free" as const,
        githubStars: 75000,
        pros: ["Fastest runtime", "Batteries-included", "Drop-in Node replacement"],
        cons: ["Less mature", "Some compatibility issues"],
        bestFor: ["Speed-critical apps", "All-in-one tooling", "Modern projects"],
        features: ["Built-in bundler", "Test runner", "Package manager", "JSC engine"],
        tags: ["javascript", "fast", "bundler", "runtime"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Deno",
        slug: "deno",
        tagline: "A modern runtime for JavaScript and TypeScript",
        description: "Secure runtime with TypeScript support and web standards",
        websiteUrl: "https://deno.land",
        githubUrl: "https://github.com/denoland/deno",
        categoryId: categoryIds["backend"],
        pricingModel: "free" as const,
        githubStars: 98000,
        pros: ["Security model", "TypeScript native", "Modern APIs"],
        cons: ["Smaller ecosystem", "npm compatibility improving"],
        bestFor: ["Security-focused", "TypeScript-first", "Web standards"],
        features: ["Secure by default", "Built-in tooling", "Web standards", "npm compat"],
        tags: ["typescript", "secure", "runtime", "modern"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Go",
        slug: "go",
        tagline: "Build simple, secure, scalable systems",
        description: "Compiled language with excellent concurrency and fast compilation",
        websiteUrl: "https://go.dev",
        githubUrl: "https://github.com/golang/go",
        categoryId: categoryIds["backend"],
        pricingModel: "free" as const,
        githubStars: 125000,
        pros: ["Fast", "Simple", "Great for APIs"],
        cons: ["Verbose error handling", "Limited generics"],
        bestFor: ["High-performance APIs", "Microservices", "CLI tools"],
        features: ["Goroutines", "Fast compilation", "Static binary", "Concurrency"],
        tags: ["compiled", "fast", "concurrency", "google"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Rust",
        slug: "rust",
        tagline: "A language empowering everyone to build reliable software",
        description: "Systems language with memory safety and zero-cost abstractions",
        websiteUrl: "https://www.rust-lang.org",
        githubUrl: "https://github.com/rust-lang/rust",
        categoryId: categoryIds["backend"],
        pricingModel: "free" as const,
        githubStars: 100000,
        pros: ["Fastest", "Safest", "WebAssembly support"],
        cons: ["Steep learning curve", "Slower development"],
        bestFor: ["Performance-critical", "Systems programming", "WebAssembly"],
        features: ["Memory safety", "Fearless concurrency", "Zero-cost abstractions"],
        tags: ["systems", "safe", "fast", "wasm"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Python",
        slug: "python",
        tagline: "Programming language for everyone",
        description: "Versatile language with rich ecosystem for AI/ML and web",
        websiteUrl: "https://www.python.org",
        githubUrl: "https://github.com/python/cpython",
        categoryId: categoryIds["backend"],
        pricingModel: "free" as const,
        githubStars: 65000,
        pros: ["Best for AI/ML", "Easy to learn", "Versatile"],
        cons: ["Slower than compiled languages", "GIL"],
        bestFor: ["AI/ML", "Data science", "Rapid prototyping"],
        features: ["Rich ecosystem", "Readability", "ML libraries", "Django/FastAPI"],
        tags: ["ai", "ml", "scripting", "versatile"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Elixir",
        slug: "elixir",
        tagline: "Dynamic, functional language for scalable applications",
        description: "Functional language on BEAM VM for realtime and fault-tolerant apps",
        websiteUrl: "https://elixir-lang.org",
        githubUrl: "https://github.com/elixir-lang/elixir",
        categoryId: categoryIds["backend"],
        pricingModel: "free" as const,
        githubStars: 24000,
        pros: ["Best for realtime", "Fault-tolerant", "Scalable"],
        cons: ["Smaller ecosystem", "Steeper learning curve"],
        bestFor: ["Realtime apps", "High concurrency", "Fault tolerance"],
        features: ["Phoenix framework", "LiveView", "OTP", "BEAM VM"],
        tags: ["functional", "realtime", "fault-tolerant", "beam"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      // Databases
      {
        name: "Supabase",
        slug: "supabase",
        tagline: "The open source Firebase alternative",
        description: "PostgreSQL-based BaaS with auth, storage, and realtime",
        websiteUrl: "https://supabase.com",
        githubUrl: "https://github.com/supabase/supabase",
        categoryId: categoryIds["databases"],
        pricingModel: "freemium" as const,
        githubStars: 75000,
        pros: ["All-in-one", "Great DX", "Open source"],
        cons: ["Vertical scaling limits"],
        bestFor: ["Full-stack apps", "MVPs", "PostgreSQL fans"],
        features: ["Auth", "Realtime", "Storage", "Edge Functions", "Vector"],
        tags: ["postgres", "baas", "realtime", "auth"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Convex",
        slug: "convex",
        tagline: "The fullstack TypeScript platform",
        description: "Reactive backend with realtime queries and serverless functions",
        websiteUrl: "https://convex.dev",
        categoryId: categoryIds["databases"],
        pricingModel: "freemium" as const,
        pros: ["True reactivity", "Great DX", "TypeScript native"],
        cons: ["Vendor lock-in", "Newer platform"],
        bestFor: ["Realtime apps", "TypeScript projects", "Reactive UIs"],
        features: ["Reactive queries", "Serverless functions", "File storage", "Scheduling"],
        tags: ["reactive", "typescript", "realtime", "serverless"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "PlanetScale",
        slug: "planetscale",
        tagline: "The MySQL-compatible serverless database",
        description: "MySQL database powered by Vitess with branching",
        websiteUrl: "https://planetscale.com",
        categoryId: categoryIds["databases"],
        pricingModel: "paid" as const,
        pros: ["Horizontal scaling", "Great DX", "Branching"],
        cons: ["No free tier", "No foreign keys"],
        bestFor: ["High-scale MySQL", "Branching workflows"],
        features: ["Branching", "Non-blocking schema changes", "Insights"],
        tags: ["mysql", "vitess", "branching", "scale"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Neon",
        slug: "neon",
        tagline: "Serverless Postgres",
        description: "Serverless PostgreSQL with branching and scale-to-zero",
        websiteUrl: "https://neon.tech",
        githubUrl: "https://github.com/neondatabase/neon",
        categoryId: categoryIds["databases"],
        pricingModel: "freemium" as const,
        githubStars: 15000,
        pros: ["True serverless", "Branching", "Generous free tier"],
        cons: ["Cold starts", "Newer platform"],
        bestFor: ["Serverless apps", "Branching workflows", "Cost optimization"],
        features: ["Branching", "Autoscaling", "Scale-to-zero", "PostgreSQL"],
        tags: ["postgres", "serverless", "branching", "scale"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Turso",
        slug: "turso",
        tagline: "SQLite for Production",
        description: "Edge SQLite database with global replication",
        websiteUrl: "https://turso.tech",
        githubUrl: "https://github.com/tursodatabase/libsql",
        categoryId: categoryIds["databases"],
        pricingModel: "freemium" as const,
        githubStars: 10000,
        pros: ["Lowest latency", "Edge-native", "SQLite compatible"],
        cons: ["SQLite limitations", "Newer platform"],
        bestFor: ["Edge-first apps", "Embedded databases", "Low latency"],
        features: ["Edge replication", "Embedded mode", "Sync", "libSQL"],
        tags: ["sqlite", "edge", "embedded", "low-latency"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "MongoDB Atlas",
        slug: "mongodb",
        tagline: "The developer data platform",
        description: "Document database with flexible schemas and Atlas Search",
        websiteUrl: "https://www.mongodb.com/atlas",
        categoryId: categoryIds["databases"],
        pricingModel: "freemium" as const,
        pros: ["Flexible schema", "Scalable", "Good for prototyping"],
        cons: ["Not ideal for relational data", "Costs at scale"],
        bestFor: ["Flexible schemas", "Document storage", "Rapid prototyping"],
        features: ["Flexible schema", "Aggregation", "Atlas Search", "Charts"],
        tags: ["nosql", "document", "flexible", "atlas"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Upstash",
        slug: "upstash",
        tagline: "Serverless Data Platform",
        description: "Serverless Redis and Kafka with REST API",
        websiteUrl: "https://upstash.com",
        categoryId: categoryIds["databases"],
        pricingModel: "freemium" as const,
        pros: ["True serverless", "Great free tier", "Simple"],
        cons: ["Limited to Redis/Kafka use cases"],
        bestFor: ["Caching", "Rate limiting", "Queues"],
        features: ["Serverless Redis", "REST API", "Global replication", "QStash"],
        tags: ["redis", "serverless", "caching", "queues"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      // Auth
      {
        name: "Clerk",
        slug: "clerk",
        tagline: "More than authentication",
        description: "Complete user management with beautiful pre-built components",
        websiteUrl: "https://clerk.com",
        categoryId: categoryIds["auth"],
        pricingModel: "freemium" as const,
        pros: ["Best DX", "Beautiful UI", "Fast integration"],
        cons: ["Vendor lock-in", "Costs at scale"],
        bestFor: ["Modern apps", "Great DX", "Pre-built UI"],
        features: ["Pre-built components", "Organizations", "MFA", "Webhooks"],
        tags: ["auth", "user-management", "components", "modern"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Auth0",
        slug: "auth0",
        tagline: "Secure access for everyone",
        description: "Enterprise identity platform with extensive customization",
        websiteUrl: "https://auth0.com",
        categoryId: categoryIds["auth"],
        pricingModel: "freemium" as const,
        pros: ["Enterprise features", "Mature", "Extensible"],
        cons: ["Complex", "Expensive at scale"],
        bestFor: ["Enterprise", "Complex auth flows", "SSO"],
        features: ["Universal login", "SSO", "MFA", "Extensibility"],
        tags: ["auth", "enterprise", "sso", "identity"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "NextAuth.js / Auth.js",
        slug: "nextauth",
        tagline: "Authentication for the Web",
        description: "Open source authentication library for Next.js and beyond",
        websiteUrl: "https://authjs.dev",
        githubUrl: "https://github.com/nextauthjs/next-auth",
        categoryId: categoryIds["auth"],
        pricingModel: "free" as const,
        githubStars: 25000,
        pros: ["Free", "Flexible", "Self-hosted"],
        cons: ["More setup", "Self-managed"],
        bestFor: ["Self-hosted auth", "Next.js apps", "Full control"],
        features: ["Multiple providers", "Database adapters", "JWT/Session", "OAuth"],
        tags: ["auth", "open-source", "nextjs", "self-hosted"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Supabase Auth",
        slug: "supabase-auth",
        tagline: "Auth integrated with your database",
        description: "Authentication service integrated with Supabase and PostgreSQL RLS",
        websiteUrl: "https://supabase.com/auth",
        categoryId: categoryIds["auth"],
        pricingModel: "freemium" as const,
        pros: ["Integrated with Supabase", "RLS support", "Free"],
        cons: ["Tied to Supabase ecosystem"],
        bestFor: ["Supabase users", "PostgreSQL RLS", "All-in-one"],
        features: ["Social login", "Magic links", "RLS integration", "MFA"],
        tags: ["auth", "supabase", "postgres", "rls"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Firebase Auth",
        slug: "firebase-auth",
        tagline: "Drop-in authentication",
        description: "Easy authentication with Google ecosystem integration",
        websiteUrl: "https://firebase.google.com/products/auth",
        categoryId: categoryIds["auth"],
        pricingModel: "freemium" as const,
        pros: ["Free", "Easy setup", "Mobile SDKs"],
        cons: ["Google lock-in", "Limited customization"],
        bestFor: ["Firebase users", "Mobile apps", "Quick setup"],
        features: ["Social login", "Phone auth", "Anonymous auth", "Multi-platform"],
        tags: ["auth", "firebase", "google", "mobile"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      // Hosting
      {
        name: "Vercel",
        slug: "vercel",
        tagline: "Develop. Preview. Ship.",
        description: "Frontend cloud platform optimized for Next.js",
        websiteUrl: "https://vercel.com",
        categoryId: categoryIds["hosting"],
        pricingModel: "freemium" as const,
        pros: ["Best Next.js support", "Great DX", "Fast"],
        cons: ["Expensive at scale", "Vendor lock-in"],
        bestFor: ["Next.js apps", "Frontend", "Serverless"],
        features: ["Edge Functions", "Preview deployments", "Analytics", "KV"],
        tags: ["hosting", "nextjs", "edge", "serverless"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Railway",
        slug: "railway",
        tagline: "Bring your code, we'll handle the rest",
        description: "Simple app platform with databases included",
        websiteUrl: "https://railway.app",
        categoryId: categoryIds["hosting"],
        pricingModel: "freemium" as const,
        pros: ["Simple", "Great DX", "Fair pricing"],
        cons: ["Less edge presence"],
        bestFor: ["Full-stack apps", "Databases", "Simplicity"],
        features: ["One-click deploys", "Databases", "Environments", "Cron"],
        tags: ["hosting", "paas", "databases", "simple"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Netlify",
        slug: "netlify",
        tagline: "The platform developers love",
        description: "Web platform for static sites and JAMstack applications",
        websiteUrl: "https://www.netlify.com",
        categoryId: categoryIds["hosting"],
        pricingModel: "freemium" as const,
        pros: ["Great free tier", "Easy setup", "Good for static sites"],
        cons: ["Less optimized for Next.js than Vercel"],
        bestFor: ["Static sites", "JAMstack", "Simple deployments"],
        features: ["Forms", "Identity", "Edge functions", "Split testing"],
        tags: ["hosting", "jamstack", "static", "edge"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Fly.io",
        slug: "flyio",
        tagline: "Run your app close to your users",
        description: "Global app platform with edge deployment and containers",
        websiteUrl: "https://fly.io",
        categoryId: categoryIds["hosting"],
        pricingModel: "freemium" as const,
        pros: ["True global distribution", "Flexible", "Containers"],
        cons: ["More complex than competitors"],
        bestFor: ["Global distribution", "Containers", "Edge apps"],
        features: ["Global edge", "Machines API", "Postgres", "Volumes"],
        tags: ["hosting", "edge", "containers", "global"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Render",
        slug: "render",
        tagline: "Cloud hosting for developers",
        description: "Simple cloud platform as Heroku alternative",
        websiteUrl: "https://render.com",
        categoryId: categoryIds["hosting"],
        pricingModel: "freemium" as const,
        pros: ["Simple", "Good free tier", "Heroku-like"],
        cons: ["Cold starts on free tier"],
        bestFor: ["Heroku alternative", "Simplicity", "Full-stack"],
        features: ["Auto-deploy", "Managed databases", "Cron", "Blueprints"],
        tags: ["hosting", "paas", "heroku", "simple"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Cloudflare Workers",
        slug: "cloudflare-workers",
        tagline: "Build serverless applications",
        description: "Edge runtime with V8 isolates and global distribution",
        websiteUrl: "https://workers.cloudflare.com",
        categoryId: categoryIds["hosting"],
        pricingModel: "freemium" as const,
        pros: ["Fastest cold starts", "Global", "Cheap"],
        cons: ["Runtime limitations", "Learning curve"],
        bestFor: ["Edge computing", "Global latency", "Serverless"],
        features: ["V8 isolates", "KV storage", "D1", "R2", "Durable Objects"],
        tags: ["edge", "serverless", "cloudflare", "fast"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      // Realtime
      {
        name: "Liveblocks",
        slug: "liveblocks",
        tagline: "Build collaborative experiences",
        description: "Realtime infrastructure for collaborative applications",
        websiteUrl: "https://liveblocks.io",
        categoryId: categoryIds["realtime"],
        pricingModel: "freemium" as const,
        pros: ["Purpose-built for collaboration", "Great DX", "Pre-built components"],
        cons: ["Expensive for high usage"],
        bestFor: ["Collaborative apps", "Presence", "Cursors"],
        features: ["Presence", "Storage", "Comments", "Notifications"],
        tags: ["realtime", "collaboration", "presence", "multiplayer"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Pusher",
        slug: "pusher",
        tagline: "Powering realtime experiences",
        description: "Realtime messaging platform for chat and notifications",
        websiteUrl: "https://pusher.com",
        categoryId: categoryIds["realtime"],
        pricingModel: "freemium" as const,
        pros: ["Mature", "Reliable", "Good docs"],
        cons: ["Can get expensive", "Older API design"],
        bestFor: ["Chat", "Notifications", "Presence"],
        features: ["Channels", "Presence", "Webhooks", "Client events"],
        tags: ["realtime", "messaging", "chat", "notifications"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Ably",
        slug: "ably",
        tagline: "Realtime experience infrastructure",
        description: "Enterprise-grade realtime platform with global distribution",
        websiteUrl: "https://ably.com",
        categoryId: categoryIds["realtime"],
        pricingModel: "freemium" as const,
        pros: ["Enterprise-grade", "Reliable", "Global"],
        cons: ["Complex pricing", "Enterprise focus"],
        bestFor: ["Enterprise realtime", "Reliability", "Scale"],
        features: ["Pub/sub", "Presence", "History", "Integrations"],
        tags: ["realtime", "enterprise", "pubsub", "reliable"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Socket.io",
        slug: "socketio",
        tagline: "Bidirectional event-based communication",
        description: "Self-hosted WebSocket library with fallback transports",
        websiteUrl: "https://socket.io",
        githubUrl: "https://github.com/socketio/socket.io",
        categoryId: categoryIds["realtime"],
        pricingModel: "free" as const,
        githubStars: 62000,
        pros: ["Free", "Flexible", "Mature"],
        cons: ["Self-hosted complexity", "Scaling challenges"],
        bestFor: ["Self-hosted realtime", "Node.js apps", "Full control"],
        features: ["Fallback transports", "Rooms", "Namespaces", "Broadcasting"],
        tags: ["realtime", "websocket", "self-hosted", "node"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      // LLMs
      {
        name: "Claude 3.5 Sonnet",
        slug: "claude-sonnet",
        tagline: "Best-in-class coding AI",
        description: "Anthropic's flagship model for coding and analysis",
        websiteUrl: "https://anthropic.com",
        categoryId: categoryIds["llms"],
        pricingModel: "paid" as const,
        pros: ["Best coding accuracy", "200K context", "Fast"],
        cons: ["Can be conservative"],
        bestFor: ["Coding", "Analysis", "Long context"],
        features: ["200K context", "Artifacts", "Tool use", "Vision"],
        tags: ["llm", "anthropic", "coding", "fast"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "GPT-4o",
        slug: "gpt-4o",
        tagline: "OpenAI's flagship multimodal model",
        description: "Fast, capable model for text, vision, and audio",
        websiteUrl: "https://openai.com",
        categoryId: categoryIds["llms"],
        pricingModel: "paid" as const,
        pros: ["Multimodal", "Fast", "Large ecosystem"],
        cons: ["Can be lazy on complex tasks"],
        bestFor: ["General tasks", "Multimodal", "Ecosystem"],
        features: ["128K context", "Vision", "Audio", "Function calling"],
        tags: ["llm", "openai", "multimodal", "popular"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Gemini 1.5 Pro",
        slug: "gemini-pro",
        tagline: "Google's long-context model",
        description: "2M token context window with multimodal capabilities",
        websiteUrl: "https://deepmind.google/technologies/gemini/",
        categoryId: categoryIds["llms"],
        pricingModel: "freemium" as const,
        pros: ["Largest context (2M)", "Good reasoning", "Free tier"],
        cons: ["Inconsistent quality"],
        bestFor: ["Long documents", "Multimodal", "Budget"],
        features: ["2M context", "Vision", "Audio", "Google integration"],
        tags: ["llm", "google", "long-context", "multimodal"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "DeepSeek V3",
        slug: "deepseek-v3",
        tagline: "Cost-effective frontier model",
        description: "High-performance model at fraction of the cost",
        websiteUrl: "https://deepseek.com",
        categoryId: categoryIds["llms"],
        pricingModel: "paid" as const,
        pros: ["Cheapest frontier model", "Good at math", "Open weights"],
        cons: ["China-based", "Less polished"],
        bestFor: ["Budget projects", "Technical tasks", "Math"],
        features: ["128K context", "MoE architecture", "Open weights"],
        tags: ["llm", "budget", "math", "open"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Llama 3.1",
        slug: "llama",
        tagline: "Open foundation model by Meta",
        description: "Open-weight model available for self-hosting",
        websiteUrl: "https://llama.meta.com",
        githubUrl: "https://github.com/meta-llama/llama",
        categoryId: categoryIds["llms"],
        pricingModel: "free" as const,
        githubStars: 60000,
        pros: ["Open weights", "Self-hostable", "No API costs"],
        cons: ["Requires infrastructure", "Less capable than closed models"],
        bestFor: ["Self-hosting", "Privacy", "Cost control"],
        features: ["128K context", "Open weights", "Fine-tunable"],
        tags: ["llm", "open-source", "meta", "self-hosted"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Mistral",
        slug: "mistral",
        tagline: "Frontier AI in your hands",
        description: "European AI company with strong coding models",
        websiteUrl: "https://mistral.ai",
        categoryId: categoryIds["llms"],
        pricingModel: "freemium" as const,
        pros: ["Strong coding", "European", "Open models available"],
        cons: ["Smaller ecosystem"],
        bestFor: ["European compliance", "Coding", "Open models"],
        features: ["128K context", "Function calling", "Open weights options"],
        tags: ["llm", "european", "coding", "open"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      // Styling
      {
        name: "Tailwind CSS",
        slug: "tailwindcss",
        tagline: "Rapidly build modern websites",
        description: "Utility-first CSS framework for rapid UI development",
        websiteUrl: "https://tailwindcss.com",
        githubUrl: "https://github.com/tailwindlabs/tailwindcss",
        categoryId: categoryIds["styling"],
        pricingModel: "free" as const,
        githubStars: 85000,
        pros: ["Fast development", "Small production CSS", "Customizable"],
        cons: ["Verbose HTML", "Learning curve"],
        bestFor: ["Rapid UI development", "Consistency", "Custom designs"],
        features: ["Utility classes", "JIT compiler", "Dark mode", "Responsive"],
        tags: ["css", "utility", "responsive", "modern"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "shadcn/ui",
        slug: "shadcn",
        tagline: "Beautifully designed components",
        description: "Copy-paste component collection built on Radix UI",
        websiteUrl: "https://ui.shadcn.com",
        githubUrl: "https://github.com/shadcn-ui/ui",
        categoryId: categoryIds["styling"],
        pricingModel: "free" as const,
        githubStars: 75000,
        pros: ["Copy-paste", "Full control", "Beautiful defaults"],
        cons: ["React only", "Manual updates"],
        bestFor: ["React apps", "Customizable components", "Modern UI"],
        features: ["Radix primitives", "Tailwind styling", "Accessible", "Themeable"],
        tags: ["components", "react", "tailwind", "accessible"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Radix UI",
        slug: "radix",
        tagline: "Unstyled, accessible components",
        description: "Low-level UI primitives with accessibility built-in",
        websiteUrl: "https://www.radix-ui.com",
        githubUrl: "https://github.com/radix-ui/primitives",
        categoryId: categoryIds["styling"],
        pricingModel: "free" as const,
        githubStars: 16000,
        pros: ["Accessible", "Composable", "Unstyled"],
        cons: ["Requires styling", "React only"],
        bestFor: ["Accessible primitives", "Custom styling", "Composability"],
        features: ["Accessibility", "Composable", "Unstyled", "WAI-ARIA"],
        tags: ["components", "accessible", "primitives", "react"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Material UI",
        slug: "mui",
        tagline: "React components for faster development",
        description: "Comprehensive React component library with Material Design",
        websiteUrl: "https://mui.com",
        githubUrl: "https://github.com/mui/material-ui",
        categoryId: categoryIds["styling"],
        pricingModel: "freemium" as const,
        githubStars: 95000,
        pros: ["Comprehensive", "Mature", "Good docs"],
        cons: ["Large bundle", "Opinionated styling"],
        bestFor: ["Material Design", "Enterprise apps", "Rapid prototyping"],
        features: ["Material Design", "Theming", "Accessibility", "Pro components"],
        tags: ["components", "material", "enterprise", "react"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      // Testing
      {
        name: "Vitest",
        slug: "vitest",
        tagline: "Blazing fast unit test framework",
        description: "Vite-native test framework with Jest-compatible API",
        websiteUrl: "https://vitest.dev",
        githubUrl: "https://github.com/vitest-dev/vitest",
        categoryId: categoryIds["testing"],
        pricingModel: "free" as const,
        githubStars: 14000,
        pros: ["Fast", "Vite-native", "Jest-compatible API"],
        cons: ["Vite ecosystem focused"],
        bestFor: ["Vite projects", "Fast testing", "Modern tooling"],
        features: ["Watch mode", "Coverage", "Mocking", "TypeScript"],
        tags: ["testing", "unit", "vite", "fast"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Playwright",
        slug: "playwright",
        tagline: "Reliable end-to-end testing",
        description: "Cross-browser E2E testing with auto-wait and tracing",
        websiteUrl: "https://playwright.dev",
        githubUrl: "https://github.com/microsoft/playwright",
        categoryId: categoryIds["testing"],
        pricingModel: "free" as const,
        githubStars: 68000,
        pros: ["Multi-browser", "Auto-wait", "Great DX"],
        cons: ["Heavier than Cypress for simple tests"],
        bestFor: ["Cross-browser E2E", "Modern web", "CI/CD"],
        features: ["Multi-browser", "Auto-wait", "Tracing", "Codegen"],
        tags: ["testing", "e2e", "browser", "microsoft"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Cypress",
        slug: "cypress",
        tagline: "Test. Automate. Accelerate.",
        description: "E2E testing with time-travel debugging",
        websiteUrl: "https://www.cypress.io",
        githubUrl: "https://github.com/cypress-io/cypress",
        categoryId: categoryIds["testing"],
        pricingModel: "freemium" as const,
        githubStars: 47000,
        pros: ["Great DX", "Time-travel debugging", "Component testing"],
        cons: ["Chrome-focused", "Slower than Playwright"],
        bestFor: ["E2E testing", "Component testing", "Developer experience"],
        features: ["Time-travel", "Real-time reloads", "Screenshots", "Videos"],
        tags: ["testing", "e2e", "component", "debugging"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      // Observability
      {
        name: "Sentry",
        slug: "sentry",
        tagline: "Application monitoring platform",
        description: "Error tracking and performance monitoring",
        websiteUrl: "https://sentry.io",
        githubUrl: "https://github.com/getsentry/sentry",
        categoryId: categoryIds["observability"],
        pricingModel: "freemium" as const,
        githubStars: 40000,
        pros: ["Comprehensive", "Great integrations", "Open source"],
        cons: ["Can get expensive"],
        bestFor: ["Error monitoring", "Performance", "Debugging"],
        features: ["Error tracking", "Performance", "Session replay", "Profiling"],
        tags: ["monitoring", "errors", "performance", "debugging"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "PostHog",
        slug: "posthog",
        tagline: "The open source product analytics suite",
        description: "All-in-one product analytics with feature flags",
        websiteUrl: "https://posthog.com",
        githubUrl: "https://github.com/PostHog/posthog",
        categoryId: categoryIds["observability"],
        pricingModel: "freemium" as const,
        githubStars: 22000,
        pros: ["Open source", "Self-hostable", "All-in-one"],
        cons: ["Can be complex to set up"],
        bestFor: ["Product analytics", "Feature flags", "Self-hosting"],
        features: ["Analytics", "Feature flags", "Session replay", "A/B testing"],
        tags: ["analytics", "product", "feature-flags", "open-source"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "LogRocket",
        slug: "logrocket",
        tagline: "Understand user experience",
        description: "Session replay and error tracking for debugging",
        websiteUrl: "https://logrocket.com",
        categoryId: categoryIds["observability"],
        pricingModel: "freemium" as const,
        pros: ["Great for debugging UX issues", "Session replay", "Error tracking"],
        cons: ["Expensive", "Privacy concerns"],
        bestFor: ["Debugging", "Session replay", "UX issues"],
        features: ["Session replay", "Error tracking", "Performance", "Rage clicks"],
        tags: ["monitoring", "session-replay", "debugging", "ux"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      // Vibe Coding - Browser-based Tools
      {
        name: "Bolt.new",
        slug: "bolt-new",
        tagline: "Prompt, run, edit, and deploy full-stack apps",
        description: "Browser-based AI coding agent for building and deploying full-stack web applications through conversational prompts",
        websiteUrl: "https://bolt.new",
        categoryId: categoryIds["vibe-coding"],
        pricingModel: "freemium" as const,
        pros: ["Full npm ecosystem access", "Instant deployment", "No setup required"],
        cons: ["Browser-based limitations", "Subscription for heavy use"],
        bestFor: ["Rapid prototyping", "Full-stack apps", "Quick deployments"],
        features: ["AI code generation", "Integrated terminal", "Auto deployment", "React/Vue/Next.js support"],
        tags: ["vibe-coding", "browser", "fullstack", "ai"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Lovable",
        slug: "lovable",
        tagline: "Idea to app in seconds",
        description: "AI-powered web development platform for creating apps through conversational interaction with Supabase integration",
        websiteUrl: "https://lovable.dev",
        categoryId: categoryIds["vibe-coding"],
        pricingModel: "freemium" as const,
        pros: ["Superhuman full stack engineer", "Supabase integration", "GitHub sync"],
        cons: ["Learning curve for complex apps"],
        bestFor: ["MVPs", "Prototypes", "Full-stack apps with database"],
        features: ["Collaborative workspaces", "GitHub sync", "Supabase integration", "MCP server support"],
        tags: ["vibe-coding", "supabase", "fullstack", "ai"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "v0",
        slug: "v0",
        tagline: "AI-powered interface builder by Vercel",
        description: "Generates React applications from text prompts and designs using Next.js, React, and Tailwind CSS",
        websiteUrl: "https://v0.dev",
        categoryId: categoryIds["vibe-coding"],
        pricingModel: "freemium" as const,
        pros: ["Vercel integration", "High-quality UI generation", "React/Next.js native"],
        cons: ["Frontend focused", "Limited backend capabilities"],
        bestFor: ["UI generation", "React components", "Frontend prototyping"],
        features: ["Text to UI", "Next.js generation", "Tailwind CSS", "Vercel deployment"],
        tags: ["vibe-coding", "ui", "react", "vercel"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Replit",
        slug: "replit",
        tagline: "Build software collaboratively with AI",
        description: "Browser-based IDE with Ghostwriter AI for building and deploying apps",
        websiteUrl: "https://replit.com",
        categoryId: categoryIds["vibe-coding"],
        pricingModel: "freemium" as const,
        pros: ["Instant coding environment", "Collaborative", "Multi-language support"],
        cons: ["Performance limitations", "Resource constraints on free tier"],
        bestFor: ["Learning", "Collaboration", "Quick prototypes"],
        features: ["Ghostwriter AI", "Instant hosting", "Multiplayer", "100+ languages"],
        tags: ["vibe-coding", "browser", "collaborative", "education"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Firebase Studio",
        slug: "firebase-studio",
        tagline: "Build and ship production-quality AI apps",
        description: "Google's agentic cloud-based development environment for full-stack AI apps",
        websiteUrl: "https://studio.firebase.google.com",
        categoryId: categoryIds["vibe-coding"],
        pricingModel: "freemium" as const,
        pros: ["Google ecosystem", "Production-ready", "AI-native"],
        cons: ["Google lock-in", "Newer platform"],
        bestFor: ["AI apps", "Firebase projects", "Google Cloud users"],
        features: ["Agentic development", "Firebase integration", "AI-powered", "Cloud deployment"],
        tags: ["vibe-coding", "firebase", "google", "ai"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Kiro",
        slug: "kiro",
        tagline: "The AI IDE for prototype to production",
        description: "AI-powered IDE with spec-driven development and autonomous task execution by Amazon",
        websiteUrl: "https://kiro.dev",
        categoryId: categoryIds["vibe-coding"],
        pricingModel: "freemium" as const,
        pros: ["Spec-driven development", "Multimodal inputs", "Agent hooks"],
        cons: ["Newer platform", "Amazon ecosystem"],
        bestFor: ["Structured development", "Enterprise", "AWS users"],
        features: ["Spec-driven", "Autonomous tasks", "Claude Sonnet integration", "Agent hooks"],
        tags: ["vibe-coding", "amazon", "spec-driven", "enterprise"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Devin",
        slug: "devin",
        tagline: "The first AI software engineer",
        description: "Autonomous AI software engineer that completes complex engineering tasks across codebases",
        websiteUrl: "https://devin.ai",
        categoryId: categoryIds["vibe-coding"],
        pricingModel: "paid" as const,
        pros: ["Fully autonomous", "Handles complex tasks", "GitHub/Slack/Jira integration"],
        cons: ["Expensive", "Less control"],
        bestFor: ["Code migration", "Refactoring", "Autonomous development"],
        features: ["Autonomous coding", "PR creation", "Testing", "Platform integrations"],
        tags: ["vibe-coding", "autonomous", "enterprise", "ai-engineer"],
        isOpenSource: false,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Tempo",
        slug: "tempo",
        tagline: "Build React apps 10x faster with AI",
        description: "AI-powered React app builder with visual editing",
        websiteUrl: "https://www.tempo.new",
        categoryId: categoryIds["vibe-coding"],
        pricingModel: "freemium" as const,
        pros: ["React-focused", "Visual editing", "Fast iteration"],
        cons: ["React only", "Newer platform"],
        bestFor: ["React apps", "Visual development", "Rapid prototyping"],
        features: ["AI generation", "Visual editor", "React native", "Component library"],
        tags: ["vibe-coding", "react", "visual", "fast"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Create.xyz",
        slug: "create-xyz",
        tagline: "Turn your words into sites, tools, and apps",
        description: "AI platform for creating websites and applications from natural language",
        websiteUrl: "https://www.create.xyz",
        categoryId: categoryIds["vibe-coding"],
        pricingModel: "freemium" as const,
        pros: ["Simple interface", "Quick results", "No coding required"],
        cons: ["Limited customization"],
        bestFor: ["Non-developers", "Quick sites", "Simple apps"],
        features: ["Natural language", "Instant preview", "Deployment", "Templates"],
        tags: ["vibe-coding", "no-code", "simple", "websites"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Rork",
        slug: "rork",
        tagline: "Build any mobile app, fast",
        description: "AI-powered mobile app builder for rapid development",
        websiteUrl: "https://rork.app",
        categoryId: categoryIds["vibe-coding"],
        pricingModel: "freemium" as const,
        pros: ["Mobile-focused", "Fast development", "Cross-platform"],
        cons: ["Mobile only", "Newer platform"],
        bestFor: ["Mobile apps", "Cross-platform", "Rapid development"],
        features: ["AI generation", "Mobile native", "Cross-platform", "Fast iteration"],
        tags: ["vibe-coding", "mobile", "cross-platform", "fast"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      // CLI Agents
      {
        name: "Claude Code",
        slug: "claude-code",
        tagline: "Agentic coding in your terminal",
        description: "Anthropic's CLI-based agentic coding assistant with deep codebase understanding",
        websiteUrl: "https://www.anthropic.com/claude-code",
        githubUrl: "https://github.com/anthropics/claude-code",
        categoryId: categoryIds["cli-agents"],
        pricingModel: "paid" as const,
        pros: ["Deep codebase understanding", "Multi-file coordination", "VS Code/JetBrains integration"],
        cons: ["Requires Claude subscription", "CLI-based"],
        bestFor: ["Terminal workflows", "Complex refactoring", "Codebase-wide changes"],
        features: ["Agentic search", "Multi-file editing", "Git integration", "IDE integrations"],
        tags: ["cli", "anthropic", "agentic", "terminal"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "OpenAI Codex CLI",
        slug: "openai-codex-cli",
        tagline: "Lightweight coding agent in your terminal",
        description: "OpenAI's experimental terminal-based coding agent with configurable sandbox modes",
        websiteUrl: "https://openai.com/codex",
        githubUrl: "https://github.com/openai/codex",
        categoryId: categoryIds["cli-agents"],
        pricingModel: "freemium" as const,
        pros: ["Open source", "Configurable sandbox", "Multiple model support"],
        cons: ["Experimental", "Requires API key"],
        bestFor: ["Terminal workflows", "Code generation", "Security-conscious development"],
        features: ["Sandbox execution", "Code generation", "Refactoring", "Security scanning"],
        tags: ["cli", "openai", "open-source", "sandbox"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Aider",
        slug: "aider",
        tagline: "AI pair programming in your terminal",
        description: "Terminal-based AI pair programming tool with Git integration",
        websiteUrl: "https://aider.chat",
        githubUrl: "https://github.com/paul-gauthier/aider",
        categoryId: categoryIds["cli-agents"],
        pricingModel: "free" as const,
        githubStars: 25000,
        pros: ["Open source", "Git-aware", "Multiple LLM support"],
        cons: ["CLI only", "Learning curve"],
        bestFor: ["Pair programming", "Git workflows", "Terminal users"],
        features: ["Git integration", "Multi-LLM", "Voice coding", "Linting"],
        tags: ["cli", "open-source", "git", "pair-programming"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Goose",
        slug: "goose",
        tagline: "Your on-machine AI agent",
        description: "Local AI agent by Block with MCP support and extensibility",
        websiteUrl: "https://block.github.io/goose",
        githubUrl: "https://github.com/block/goose",
        categoryId: categoryIds["cli-agents"],
        pricingModel: "free" as const,
        githubStars: 5000,
        pros: ["Local execution", "MCP support", "Any LLM"],
        cons: ["Requires setup", "Local resources"],
        bestFor: ["Privacy-focused", "Local development", "MCP extensions"],
        features: ["MCP servers", "Any LLM", "Local execution", "Extensible"],
        tags: ["cli", "local", "mcp", "block"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Gemini CLI",
        slug: "gemini-cli",
        tagline: "Gemini AI in your terminal",
        description: "Google's open source terminal-based AI agent with Gemini 2.5 Pro",
        websiteUrl: "https://google-gemini.github.io/gemini-cli",
        githubUrl: "https://github.com/google-gemini/gemini-cli",
        categoryId: categoryIds["cli-agents"],
        pricingModel: "freemium" as const,
        pros: ["1M token context", "Google Search integration", "Open source"],
        cons: ["Google ecosystem", "Newer tool"],
        bestFor: ["Long context", "Google users", "Terminal workflows"],
        features: ["1M context", "Google Search", "File operations", "Multimodal"],
        tags: ["cli", "google", "gemini", "open-source"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Cline",
        slug: "cline",
        tagline: "AI assistant for your CLI and Editor",
        description: "Open source AI coding agent for VS Code with autonomous capabilities",
        websiteUrl: "https://cline.bot",
        githubUrl: "https://github.com/cline/cline",
        categoryId: categoryIds["cli-agents"],
        pricingModel: "free" as const,
        githubStars: 30000,
        pros: ["VS Code integration", "Autonomous", "Multi-model support"],
        cons: ["VS Code only", "Requires API keys"],
        bestFor: ["VS Code users", "Autonomous coding", "Browser automation"],
        features: ["File editing", "Terminal commands", "Browser automation", "Human approval workflows"],
        tags: ["cli", "vscode", "autonomous", "open-source"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Roo Code",
        slug: "roo-code",
        tagline: "AI assistant with multiple roles",
        description: "Fork of Cline with extra features supporting multiple agent roles",
        websiteUrl: "https://github.com/RooVetGit/Roo-Code",
        githubUrl: "https://github.com/RooVetGit/Roo-Code",
        categoryId: categoryIds["cli-agents"],
        pricingModel: "free" as const,
        pros: ["Multiple roles", "Enhanced features", "Open source"],
        cons: ["Fork maintenance", "Smaller community"],
        bestFor: ["Role-based development", "Architect/QA/PM workflows"],
        features: ["Multiple roles", "Boomerang tasks", "Enhanced Cline features"],
        tags: ["cli", "vscode", "roles", "open-source"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "OpenHands",
        slug: "openhands",
        tagline: "Open source AI software developer",
        description: "Autonomous AI software development agent platform with GUI and CLI",
        websiteUrl: "https://www.all-hands.dev",
        githubUrl: "https://github.com/All-Hands-AI/OpenHands",
        categoryId: categoryIds["cli-agents"],
        pricingModel: "free" as const,
        githubStars: 45000,
        pros: ["Fully autonomous", "GUI and CLI", "Multi-LLM support"],
        cons: ["Resource intensive", "Complex setup"],
        bestFor: ["Autonomous development", "Complex tasks", "Self-hosted"],
        features: ["Autonomous coding", "Terminal commands", "Web browsing", "API calls"],
        tags: ["cli", "autonomous", "open-source", "self-hosted"],
        isOpenSource: true,
        isActive: true,
        isFeatured: true,
      },
      {
        name: "Amp",
        slug: "amp",
        tagline: "Frontier coding agent by Sourcegraph",
        description: "AI coding agent for terminal and editor with LLM flexibility",
        websiteUrl: "https://ampcode.com",
        categoryId: categoryIds["cli-agents"],
        pricingModel: "freemium" as const,
        pros: ["Sourcegraph integration", "Multiple LLMs", "Terminal and editor"],
        cons: ["Newer platform"],
        bestFor: ["Large codebases", "Sourcegraph users", "Flexible LLM choice"],
        features: ["Terminal agent", "Editor integration", "Multi-LLM", "Codebase search"],
        tags: ["cli", "sourcegraph", "multi-llm", "enterprise"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Warp",
        slug: "warp",
        tagline: "The terminal for the 21st century",
        description: "Rust-based terminal with native AI integration",
        websiteUrl: "https://www.warp.dev",
        categoryId: categoryIds["cli-agents"],
        pricingModel: "freemium" as const,
        pros: ["Modern terminal", "Native AI", "Fast (Rust-based)"],
        cons: ["macOS/Linux only", "Closed source"],
        bestFor: ["Modern terminal users", "AI-assisted commands", "Developer productivity"],
        features: ["AI commands", "Blocks", "Workflows", "Collaboration"],
        tags: ["terminal", "rust", "ai", "modern"],
        isOpenSource: false,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Continue",
        slug: "continue",
        tagline: "Open-source AI code assistant",
        description: "Configurable AI assistant framework for VS Code and JetBrains",
        websiteUrl: "https://www.continue.dev",
        githubUrl: "https://github.com/continuedev/continue",
        categoryId: categoryIds["cli-agents"],
        pricingModel: "free" as const,
        githubStars: 20000,
        pros: ["Open source", "Highly configurable", "Multi-IDE support"],
        cons: ["Requires configuration", "Self-managed"],
        bestFor: ["Custom setups", "Privacy-focused", "IDE integration"],
        features: ["Custom models", "Prompts", "Rules", "Docs integration"],
        tags: ["cli", "open-source", "configurable", "multi-ide"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Kilo Code",
        slug: "kilo-code",
        tagline: "AI coding agent with 400+ model support",
        description: "Open-source VS Code AI coding agent with multiple agent modes",
        websiteUrl: "https://kilocode.ai",
        githubUrl: "https://github.com/Kilo-Org/kilocode",
        categoryId: categoryIds["cli-agents"],
        pricingModel: "free" as const,
        pros: ["400+ models", "Multiple modes", "No API key required via OpenRouter"],
        cons: ["VS Code only", "Newer platform"],
        bestFor: ["Model flexibility", "Role-based development", "Budget-conscious"],
        features: ["Orchestrator mode", "Architect mode", "Memory bank", "Browser automation"],
        tags: ["cli", "vscode", "multi-model", "open-source"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
      {
        name: "Dyad",
        slug: "dyad",
        tagline: "Free, local, open-source AI app builder",
        description: "Local AI app builder that runs entirely on your machine",
        websiteUrl: "https://www.dyad.sh",
        categoryId: categoryIds["cli-agents"],
        pricingModel: "free" as const,
        pros: ["Completely local", "Free", "Open source"],
        cons: ["Requires local resources", "Less powerful than cloud"],
        bestFor: ["Privacy-focused", "Offline development", "Local-first"],
        features: ["Local execution", "App building", "No cloud required"],
        tags: ["local", "open-source", "free", "privacy"],
        isOpenSource: true,
        isActive: true,
        isFeatured: false,
      },
    ];

    for (const tool of tools) {
      const toolId = await ctx.db.insert("tools", tool);
      
      // Add pricing tiers based on tool
      if (tool.slug === "cursor") {
        await ctx.db.insert("pricingTiers", {
          toolId,
          name: "Free",
          priceMonthly: 0,
          features: ["2000 completions", "50 slow premium requests"],
          isPopular: false,
          sortOrder: 1,
        });
        await ctx.db.insert("pricingTiers", {
          toolId,
          name: "Pro",
          priceMonthly: 20,
          features: ["Unlimited completions", "500 fast premium requests", "Unlimited slow"],
          isPopular: true,
          sortOrder: 2,
        });
      }
      
      if (tool.slug === "supabase") {
        await ctx.db.insert("pricingTiers", {
          toolId,
          name: "Free",
          priceMonthly: 0,
          features: ["500MB database", "1GB storage", "50K MAU"],
          isPopular: false,
          sortOrder: 1,
        });
        await ctx.db.insert("pricingTiers", {
          toolId,
          name: "Pro",
          priceMonthly: 25,
          features: ["8GB database", "100GB storage", "100K MAU", "Daily backups"],
          isPopular: true,
          sortOrder: 2,
        });
      }

      if (tool.slug === "convex") {
        await ctx.db.insert("pricingTiers", {
          toolId,
          name: "Free",
          priceMonthly: 0,
          features: ["1M function calls", "1GB storage", "Community support"],
          isPopular: false,
          sortOrder: 1,
        });
        await ctx.db.insert("pricingTiers", {
          toolId,
          name: "Pro",
          priceMonthly: 25,
          features: ["Unlimited functions", "50GB storage", "Priority support"],
          isPopular: true,
          sortOrder: 2,
        });
      }

      if (tool.slug === "vercel") {
        await ctx.db.insert("pricingTiers", {
          toolId,
          name: "Hobby",
          priceMonthly: 0,
          features: ["100GB bandwidth", "Serverless functions", "Preview deployments"],
          isPopular: false,
          sortOrder: 1,
        });
        await ctx.db.insert("pricingTiers", {
          toolId,
          name: "Pro",
          priceMonthly: 20,
          features: ["1TB bandwidth", "More functions", "Team features", "Analytics"],
          isPopular: true,
          sortOrder: 2,
        });
      }
    }

    return { message: "Database seeded successfully!", categoriesCount: categories.length, toolsCount: tools.length };
  },
});
