"use client";

import {
  Monitor,
  Bot,
  Layout,
  Layers,
  Wrench,
  Database,
  Lock,
  Cloud,
  Zap,
  Brain,
  Palette,
  FlaskConical,
  BarChart3,
  Sparkles,
  Terminal,
  Trophy,
  Search,
  Map,
  Crown,
  Swords,
  Flame,
  Shield,
  Medal,
  PartyPopper,
  Users,
  Vote,
  Coins,
  Star,
  Sprout,
  Target,
  Package,
  Frame,
  Gem,
  HelpCircle,
  Server,
  Container,
  Activity,
  TestTube,
  GitBranch,
  Code,
  Code2,
  FileCode,
  FileCode2,
  Cpu,
  Globe,
  Globe2,
  Rocket,
  Briefcase,
  Building2,
  Gamepad2,
  MessageSquare,
  MessageCircle,
  Send,
  Radio,
  Wifi,
  Eye,
  EyeOff,
  Key,
  KeyRound,
  Fingerprint,
  UserCheck,
  ShieldCheck,
  Upload,
  Download,
  HardDrive,
  FolderOpen,
  FileJson,
  FileText,
  Files,
  Image,
  Video,
  Music,
  Mic,
  Speaker,
  Headphones,
  Camera,
  Smartphone,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Printer,
  Mouse,
  Keyboard,
  Usb,
  Bluetooth,
  Battery,
  BatteryCharging,
  Power,
  Settings,
  Settings2,
  Cog,
  SlidersHorizontal,
  ToggleLeft,
  ToggleRight,
  RefreshCw,
  RefreshCcw,
  RotateCw,
  RotateCcw,
  Repeat,
  Shuffle,
  Play,
  Pause,
  Square,
  Circle,
  Triangle,
  Hexagon,
  Octagon,
  Pentagon,
  Diamond,
  Heart,
  HeartHandshake,
  ThumbsUp,
  ThumbsDown,
  Hand,
  Pointer,
  Move,
  Maximize,
  Minimize,
  Expand,
  Shrink,
  ZoomIn,
  ZoomOut,
  Focus,
  Crosshair,
  Compass,
  Navigation,
  MapPin,
  MapPinned,
  Locate,
  LocateFixed,
  LocateOff,
  Route,
  Signpost,
  Milestone,
  Flag,
  Bookmark,
  BookmarkPlus,
  Tag,
  Tags,
  Hash,
  AtSign,
  Link,
  Link2,
  Unlink,
  ExternalLink,
  Share,
  Share2,
  Forward,
  Reply,
  CornerUpLeft,
  CornerUpRight,
  CornerDownLeft,
  CornerDownRight,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowUpLeft,
  ArrowDownRight,
  ArrowDownLeft,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  Plus,
  Minus,
  X,
  Check,
  CheckCircle,
  CheckCircle2,
  XCircle,
  AlertCircle,
  AlertTriangle,
  AlertOctagon,
  Info,
  Bell,
  BellRing,
  BellOff,
  Volume,
  Volume1,
  Volume2,
  VolumeX,
  Sun,
  Moon,
  CloudSun,
  CloudMoon,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudFog,
  Wind,
  Droplet,
  Droplets,
  Thermometer,
  Umbrella,
  Snowflake,
  Leaf,
  TreePine,
  TreeDeciduous,
  Flower,
  Flower2,
  Coffee,
  Home,
  Building,
  Factory,
  Warehouse,
  Store,
  Hotel,
  Hospital,
  School,
  Library,
  Church,
  Castle,
  Landmark,
  Mountain,
  MountainSnow,
  Tent,
  Scissors,
  Pen,
  Pencil,
  Eraser,
  Highlighter,
  PenTool,
  Brush,
  PaintBucket,
  Pipette,
  Ruler,
  Scale,
  Calculator,
  Binary,
  Braces,
  Brackets,
  Regex,
  Variable,
  Component,
  Blocks,
  Box,
  Boxes,
  Cylinder,
  Orbit,
  Atom,
  Dna,
  Pill,
  Syringe,
  Stethoscope,
  Microscope,
  Telescope,
  Binoculars,
  Glasses,
  Accessibility,
  Bandage,
  Bed,
  BedDouble,
  BedSingle,
  Sofa,
  Armchair,
  Lamp,
  LampDesk,
  LampFloor,
  LampCeiling,
  Fan,
  AirVent,
  Heater,
  Plug,
  PlugZap,
  Cable,
  Router,
  Network,
  Signal,
  SignalHigh,
  SignalLow,
  SignalMedium,
  SignalZero,
  Antenna,
  Satellite,
  SatelliteDish,
  Radar,
  Scan,
  ScanLine,
  ScanFace,
  QrCode,
  Barcode,
  Nfc,
  CreditCard,
  Wallet,
  Banknote,
  PiggyBank,
  Receipt,
  Ticket,
  Gift,
  ShoppingCart,
  ShoppingBag,
  ShoppingBasket,
  PackageOpen,
  PackageCheck,
  PackageX,
  PackagePlus,
  PackageMinus,
  PackageSearch,
  Truck,
  Archive,
  ArchiveRestore,
  ArchiveX,
  Inbox,
  Mail,
  MailOpen,
  MailPlus,
  MailMinus,
  MailCheck,
  MailX,
  MailQuestion,
  MailWarning,
  MailSearch,
  Mailbox,
  SendHorizontal,
  ReplyAll,
  Paperclip,
  Clipboard,
  ClipboardList,
  ClipboardCheck,
  ClipboardX,
  ClipboardCopy,
  ClipboardPaste,
  ClipboardType,
  ClipboardSignature,
  ClipboardPen,
  Notebook,
  NotebookPen,
  NotebookText,
  NotebookTabs,
  BookOpen,
  BookOpenCheck,
  BookOpenText,
  BookMarked,
  BookText,
  BookType,
  BookCopy,
  BookDashed,
  BookHeart,
  BookImage,
  BookKey,
  BookLock,
  BookMinus,
  BookPlus,
  BookUp,
  BookUp2,
  BookUser,
  BookX,
  Book,
  GraduationCap,
  Award,
  BadgeCheck,
  BadgeAlert,
  BadgeDollarSign,
  BadgeHelp,
  BadgeInfo,
  BadgeMinus,
  BadgePercent,
  BadgePlus,
  BadgeX,
  Badge,
  Ribbon,
  Verified,
  CircleCheck,
  CircleX,
  CircleAlert,
  CircleHelp,
  CircleDot,
  CircleDotDashed,
  CircleDashed,
  CircleEllipsis,
  CircleMinus,
  CircleOff,
  CirclePause,
  CirclePlay,
  CirclePlus,
  CircleSlash,
  CircleStop,
  CircleUser,
  CircleUserRound,
  UserCircle,
  UserCircle2,
  UserCog,
  UserMinus,
  UserPlus,
  UserRound,
  UserRoundCheck,
  UserRoundCog,
  UserRoundMinus,
  UserRoundPlus,
  UserRoundSearch,
  UserRoundX,
  UserSearch,
  UserX,
  User,
  UsersRound,
  Contact,
  Contact2,
  ContactRound,
  IdCard,
  LockKeyhole,
  LockKeyholeOpen,
  LockOpen,
  Unlock,
  UnlockKeyhole,
  KeySquare,
  ShieldAlert,
  ShieldBan,
  ShieldEllipsis,
  ShieldHalf,
  ShieldMinus,
  ShieldOff,
  ShieldPlus,
  ShieldQuestion,
  ShieldX,
  Siren,
  AlarmClock,
  AlarmClockCheck,
  AlarmClockMinus,
  AlarmClockOff,
  AlarmClockPlus,
  Timer,
  TimerOff,
  TimerReset,
  Clock,
  Hourglass,
  Calendar,
  CalendarCheck,
  CalendarCheck2,
  CalendarClock,
  CalendarDays,
  CalendarMinus,
  CalendarOff,
  CalendarPlus,
  CalendarRange,
  CalendarSearch,
  CalendarX,
  CalendarX2,
  History,
  Undo,
  Undo2,
  Redo,
  Redo2,
  IterationCcw,
  IterationCw,
  Workflow,
  GitCommit,
  GitCommitHorizontal,
  GitCommitVertical,
  GitCompare,
  GitCompareArrows,
  GitFork,
  GitGraph,
  GitMerge,
  GitPullRequest,
  GitPullRequestArrow,
  GitPullRequestClosed,
  GitPullRequestCreate,
  GitPullRequestCreateArrow,
  GitPullRequestDraft,
  Github,
  Gitlab,
  Chrome,
  Figma,
  Framer,
  Instagram,
  Linkedin,
  Facebook,
  Twitter,
  Youtube,
  Twitch,
  Slack,
  Dribbble,
  type LucideProps,
} from "lucide-react";

const iconComponents: Record<string, React.ComponentType<LucideProps>> = {
  "Monitor": Monitor,
  "Bot": Bot,
  "Layout": Layout,
  "Layers": Layers,
  "Wrench": Wrench,
  "Database": Database,
  "Lock": Lock,
  "Cloud": Cloud,
  "Zap": Zap,
  "Brain": Brain,
  "Palette": Palette,
  "FlaskConical": FlaskConical,
  "BarChart3": BarChart3,
  "Sparkles": Sparkles,
  "Terminal": Terminal,
  "Trophy": Trophy,
  "Search": Search,
  "Map": Map,
  "Crown": Crown,
  "Swords": Swords,
  "Flame": Flame,
  "Shield": Shield,
  "Medal": Medal,
  "PartyPopper": PartyPopper,
  "Users": Users,
  "Vote": Vote,
  "Coins": Coins,
  "Star": Star,
  "Sprout": Sprout,
  "Target": Target,
  "Package": Package,
  "Frame": Frame,
  "Gem": Gem,
  "HelpCircle": HelpCircle,
  "Server": Server,
  "Container": Container,
  "Activity": Activity,
  "TestTube": TestTube,
  "GitBranch": GitBranch,
  "Code": Code,
  "Code2": Code2,
  "FileCode": FileCode,
  "FileCode2": FileCode2,
  "Cpu": Cpu,
  "Globe": Globe,
  "Globe2": Globe2,
  "Rocket": Rocket,
  "Briefcase": Briefcase,
  "Building2": Building2,
  "Gamepad2": Gamepad2,
  "MessageSquare": MessageSquare,
  "MessageCircle": MessageCircle,
  "Send": Send,
  "Radio": Radio,
  "Wifi": Wifi,
  "Eye": Eye,
  "EyeOff": EyeOff,
  "Key": Key,
  "KeyRound": KeyRound,
  "Fingerprint": Fingerprint,
  "UserCheck": UserCheck,
  "ShieldCheck": ShieldCheck,
  "Upload": Upload,
  "Download": Download,
  "HardDrive": HardDrive,
  "FolderOpen": FolderOpen,
  "FileJson": FileJson,
  "FileText": FileText,
  "Files": Files,
  "Image": Image,
  "Video": Video,
  "Music": Music,
  "Mic": Mic,
  "Speaker": Speaker,
  "Headphones": Headphones,
  "Camera": Camera,
  "Smartphone": Smartphone,
  "Tablet": Tablet,
  "Laptop": Laptop,
  "Tv": Tv,
  "Watch": Watch,
  "Printer": Printer,
  "Mouse": Mouse,
  "Keyboard": Keyboard,
  "Usb": Usb,
  "Bluetooth": Bluetooth,
  "Battery": Battery,
  "BatteryCharging": BatteryCharging,
  "Power": Power,
  "Settings": Settings,
  "Settings2": Settings2,
  "Cog": Cog,
  "SlidersHorizontal": SlidersHorizontal,
  "ToggleLeft": ToggleLeft,
  "ToggleRight": ToggleRight,
  "RefreshCw": RefreshCw,
  "RefreshCcw": RefreshCcw,
  "RotateCw": RotateCw,
  "RotateCcw": RotateCcw,
  "Repeat": Repeat,
  "Shuffle": Shuffle,
  "Play": Play,
  "Pause": Pause,
  "Square": Square,
  "Circle": Circle,
  "Triangle": Triangle,
  "Hexagon": Hexagon,
  "Octagon": Octagon,
  "Pentagon": Pentagon,
  "Diamond": Diamond,
  "Heart": Heart,
  "HeartHandshake": HeartHandshake,
  "ThumbsUp": ThumbsUp,
  "ThumbsDown": ThumbsDown,
  "Hand": Hand,
  "Pointer": Pointer,
  "Move": Move,
  "Maximize": Maximize,
  "Minimize": Minimize,
  "Expand": Expand,
  "Shrink": Shrink,
  "ZoomIn": ZoomIn,
  "ZoomOut": ZoomOut,
  "Focus": Focus,
  "Crosshair": Crosshair,
  "Compass": Compass,
  "Navigation": Navigation,
  "MapPin": MapPin,
  "MapPinned": MapPinned,
  "Locate": Locate,
  "LocateFixed": LocateFixed,
  "LocateOff": LocateOff,
  "Route": Route,
  "Signpost": Signpost,
  "Milestone": Milestone,
  "Flag": Flag,
  "Bookmark": Bookmark,
  "BookmarkPlus": BookmarkPlus,
  "Tag": Tag,
  "Tags": Tags,
  "Hash": Hash,
  "AtSign": AtSign,
  "Link": Link,
  "Link2": Link2,
  "Unlink": Unlink,
  "ExternalLink": ExternalLink,
  "Share": Share,
  "Share2": Share2,
  "Forward": Forward,
  "Reply": Reply,
  "CornerUpLeft": CornerUpLeft,
  "CornerUpRight": CornerUpRight,
  "CornerDownLeft": CornerDownLeft,
  "CornerDownRight": CornerDownRight,
  "ArrowUp": ArrowUp,
  "ArrowDown": ArrowDown,
  "ArrowLeft": ArrowLeft,
  "ArrowRight": ArrowRight,
  "ArrowUpRight": ArrowUpRight,
  "ArrowUpLeft": ArrowUpLeft,
  "ArrowDownRight": ArrowDownRight,
  "ArrowDownLeft": ArrowDownLeft,
  "ChevronUp": ChevronUp,
  "ChevronDown": ChevronDown,
  "ChevronLeft": ChevronLeft,
  "ChevronRight": ChevronRight,
  "ChevronsUp": ChevronsUp,
  "ChevronsDown": ChevronsDown,
  "ChevronsLeft": ChevronsLeft,
  "ChevronsRight": ChevronsRight,
  "Plus": Plus,
  "Minus": Minus,
  "X": X,
  "Check": Check,
  "CheckCircle": CheckCircle,
  "CheckCircle2": CheckCircle2,
  "XCircle": XCircle,
  "AlertCircle": AlertCircle,
  "AlertTriangle": AlertTriangle,
  "AlertOctagon": AlertOctagon,
  "Info": Info,
  "Bell": Bell,
  "BellRing": BellRing,
  "BellOff": BellOff,
  "Volume": Volume,
  "Volume1": Volume1,
  "Volume2": Volume2,
  "VolumeX": VolumeX,
  "Sun": Sun,
  "Moon": Moon,
  "CloudSun": CloudSun,
  "CloudMoon": CloudMoon,
  "CloudRain": CloudRain,
  "CloudSnow": CloudSnow,
  "CloudLightning": CloudLightning,
  "CloudFog": CloudFog,
  "Wind": Wind,
  "Droplet": Droplet,
  "Droplets": Droplets,
  "Thermometer": Thermometer,
  "Umbrella": Umbrella,
  "Snowflake": Snowflake,
  "Leaf": Leaf,
  "TreePine": TreePine,
  "TreeDeciduous": TreeDeciduous,
  "Flower": Flower,
  "Flower2": Flower2,
  "Coffee": Coffee,
  "Home": Home,
  "Building": Building,
  "Factory": Factory,
  "Warehouse": Warehouse,
  "Store": Store,
  "Hotel": Hotel,
  "Hospital": Hospital,
  "School": School,
  "Library": Library,
  "Church": Church,
  "Castle": Castle,
  "Landmark": Landmark,
  "Mountain": Mountain,
  "MountainSnow": MountainSnow,
  "Tent": Tent,
  "Scissors": Scissors,
  "Pen": Pen,
  "Pencil": Pencil,
  "Eraser": Eraser,
  "Highlighter": Highlighter,
  "PenTool": PenTool,
  "Brush": Brush,
  "PaintBucket": PaintBucket,
  "Pipette": Pipette,
  "Ruler": Ruler,
  "Scale": Scale,
  "Calculator": Calculator,
  "Binary": Binary,
  "Braces": Braces,
  "Brackets": Brackets,
  "Regex": Regex,
  "Variable": Variable,
  "Component": Component,
  "Blocks": Blocks,
  "Box": Box,
  "Boxes": Boxes,
  "Cylinder": Cylinder,
  "Orbit": Orbit,
  "Atom": Atom,
  "Dna": Dna,
  "Pill": Pill,
  "Syringe": Syringe,
  "Stethoscope": Stethoscope,
  "Microscope": Microscope,
  "Telescope": Telescope,
  "Binoculars": Binoculars,
  "Glasses": Glasses,
  "Accessibility": Accessibility,
  "Bandage": Bandage,
  "Bed": Bed,
  "BedDouble": BedDouble,
  "BedSingle": BedSingle,
  "Sofa": Sofa,
  "Armchair": Armchair,
  "Lamp": Lamp,
  "LampDesk": LampDesk,
  "LampFloor": LampFloor,
  "LampCeiling": LampCeiling,
  "Fan": Fan,
  "AirVent": AirVent,
  "Heater": Heater,
  "Plug": Plug,
  "PlugZap": PlugZap,
  "Cable": Cable,
  "Router": Router,
  "Network": Network,
  "Signal": Signal,
  "SignalHigh": SignalHigh,
  "SignalLow": SignalLow,
  "SignalMedium": SignalMedium,
  "SignalZero": SignalZero,
  "Antenna": Antenna,
  "Satellite": Satellite,
  "SatelliteDish": SatelliteDish,
  "Radar": Radar,
  "Scan": Scan,
  "ScanLine": ScanLine,
  "ScanFace": ScanFace,
  "QrCode": QrCode,
  "Barcode": Barcode,
  "Nfc": Nfc,
  "CreditCard": CreditCard,
  "Wallet": Wallet,
  "Banknote": Banknote,
  "PiggyBank": PiggyBank,
  "Receipt": Receipt,
  "Ticket": Ticket,
  "Gift": Gift,
  "ShoppingCart": ShoppingCart,
  "ShoppingBag": ShoppingBag,
  "ShoppingBasket": ShoppingBasket,
  "PackageOpen": PackageOpen,
  "PackageCheck": PackageCheck,
  "PackageX": PackageX,
  "PackagePlus": PackagePlus,
  "PackageMinus": PackageMinus,
  "PackageSearch": PackageSearch,
  "Truck": Truck,
  "Archive": Archive,
  "ArchiveRestore": ArchiveRestore,
  "ArchiveX": ArchiveX,
  "Inbox": Inbox,
  "Mail": Mail,
  "MailOpen": MailOpen,
  "MailPlus": MailPlus,
  "MailMinus": MailMinus,
  "MailCheck": MailCheck,
  "MailX": MailX,
  "MailQuestion": MailQuestion,
  "MailWarning": MailWarning,
  "MailSearch": MailSearch,
  "Mailbox": Mailbox,
  "SendHorizontal": SendHorizontal,
  "ReplyAll": ReplyAll,
  "Paperclip": Paperclip,
  "Clipboard": Clipboard,
  "ClipboardList": ClipboardList,
  "ClipboardCheck": ClipboardCheck,
  "ClipboardX": ClipboardX,
  "ClipboardCopy": ClipboardCopy,
  "ClipboardPaste": ClipboardPaste,
  "ClipboardType": ClipboardType,
  "ClipboardSignature": ClipboardSignature,
  "ClipboardPen": ClipboardPen,
  "Notebook": Notebook,
  "NotebookPen": NotebookPen,
  "NotebookText": NotebookText,
  "NotebookTabs": NotebookTabs,
  "BookOpen": BookOpen,
  "BookOpenCheck": BookOpenCheck,
  "BookOpenText": BookOpenText,
  "BookMarked": BookMarked,
  "BookText": BookText,
  "BookType": BookType,
  "BookCopy": BookCopy,
  "BookDashed": BookDashed,
  "BookHeart": BookHeart,
  "BookImage": BookImage,
  "BookKey": BookKey,
  "BookLock": BookLock,
  "BookMinus": BookMinus,
  "BookPlus": BookPlus,
  "BookUp": BookUp,
  "BookUp2": BookUp2,
  "BookUser": BookUser,
  "BookX": BookX,
  "Book": Book,
  "GraduationCap": GraduationCap,
  "Award": Award,
  "BadgeCheck": BadgeCheck,
  "BadgeAlert": BadgeAlert,
  "BadgeDollarSign": BadgeDollarSign,
  "BadgeHelp": BadgeHelp,
  "BadgeInfo": BadgeInfo,
  "BadgeMinus": BadgeMinus,
  "BadgePercent": BadgePercent,
  "BadgePlus": BadgePlus,
  "BadgeX": BadgeX,
  "Badge": Badge,
  "Ribbon": Ribbon,
  "Verified": Verified,
  "CircleCheck": CircleCheck,
  "CircleX": CircleX,
  "CircleAlert": CircleAlert,
  "CircleHelp": CircleHelp,
  "CircleDot": CircleDot,
  "CircleDotDashed": CircleDotDashed,
  "CircleDashed": CircleDashed,
  "CircleEllipsis": CircleEllipsis,
  "CircleMinus": CircleMinus,
  "CircleOff": CircleOff,
  "CirclePause": CirclePause,
  "CirclePlay": CirclePlay,
  "CirclePlus": CirclePlus,
  "CircleSlash": CircleSlash,
  "CircleStop": CircleStop,
  "CircleUser": CircleUser,
  "CircleUserRound": CircleUserRound,
  "UserCircle": UserCircle,
  "UserCircle2": UserCircle2,
  "UserCog": UserCog,
  "UserMinus": UserMinus,
  "UserPlus": UserPlus,
  "UserRound": UserRound,
  "UserRoundCheck": UserRoundCheck,
  "UserRoundCog": UserRoundCog,
  "UserRoundMinus": UserRoundMinus,
  "UserRoundPlus": UserRoundPlus,
  "UserRoundSearch": UserRoundSearch,
  "UserRoundX": UserRoundX,
  "UserSearch": UserSearch,
  "UserX": UserX,
  "User": User,
  "UsersRound": UsersRound,
  "Contact": Contact,
  "Contact2": Contact2,
  "ContactRound": ContactRound,
  "IdCard": IdCard,
  "LockKeyhole": LockKeyhole,
  "LockKeyholeOpen": LockKeyholeOpen,
  "LockOpen": LockOpen,
  "Unlock": Unlock,
  "UnlockKeyhole": UnlockKeyhole,
  "KeySquare": KeySquare,
  "ShieldAlert": ShieldAlert,
  "ShieldBan": ShieldBan,
  "ShieldEllipsis": ShieldEllipsis,
  "ShieldHalf": ShieldHalf,
  "ShieldMinus": ShieldMinus,
  "ShieldOff": ShieldOff,
  "ShieldPlus": ShieldPlus,
  "ShieldQuestion": ShieldQuestion,
  "ShieldX": ShieldX,
  "Siren": Siren,
  "AlarmClock": AlarmClock,
  "AlarmClockCheck": AlarmClockCheck,
  "AlarmClockMinus": AlarmClockMinus,
  "AlarmClockOff": AlarmClockOff,
  "AlarmClockPlus": AlarmClockPlus,
  "Timer": Timer,
  "TimerOff": TimerOff,
  "TimerReset": TimerReset,
  "Clock": Clock,
  "Hourglass": Hourglass,
  "Calendar": Calendar,
  "CalendarCheck": CalendarCheck,
  "CalendarCheck2": CalendarCheck2,
  "CalendarClock": CalendarClock,
  "CalendarDays": CalendarDays,
  "CalendarMinus": CalendarMinus,
  "CalendarOff": CalendarOff,
  "CalendarPlus": CalendarPlus,
  "CalendarRange": CalendarRange,
  "CalendarSearch": CalendarSearch,
  "CalendarX": CalendarX,
  "CalendarX2": CalendarX2,
  "History": History,
  "Undo": Undo,
  "Undo2": Undo2,
  "Redo": Redo,
  "Redo2": Redo2,
  "IterationCcw": IterationCcw,
  "IterationCw": IterationCw,
  "Workflow": Workflow,
  "GitCommit": GitCommit,
  "GitCommitHorizontal": GitCommitHorizontal,
  "GitCommitVertical": GitCommitVertical,
  "GitCompare": GitCompare,
  "GitCompareArrows": GitCompareArrows,
  "GitFork": GitFork,
  "GitGraph": GitGraph,
  "GitMerge": GitMerge,
  "GitPullRequest": GitPullRequest,
  "GitPullRequestArrow": GitPullRequestArrow,
  "GitPullRequestClosed": GitPullRequestClosed,
  "GitPullRequestCreate": GitPullRequestCreate,
  "GitPullRequestCreateArrow": GitPullRequestCreateArrow,
  "GitPullRequestDraft": GitPullRequestDraft,
  "Github": Github,
  "Gitlab": Gitlab,
  "Chrome": Chrome,
  "Figma": Figma,
  "Framer": Framer,
  "Instagram": Instagram,
  "Linkedin": Linkedin,
  "Facebook": Facebook,
  "Twitter": Twitter,
  "Youtube": Youtube,
  "Twitch": Twitch,
  "Slack": Slack,
  "Dribbble": Dribbble,
};

export const TOOL_ICONS: Record<string, string> = {
  vscode: "Code",
  cursor: "Bot",
  windsurf: "Wind",
  zed: "Zap",
  jetbrains: "Briefcase",
  neovim: "Terminal",
  "github-copilot": "Github",
  claude: "Brain",
  chatgpt: "MessageSquare",
  gemini: "Sparkles",
  cody: "Search",
  supermaven: "Rocket",
  react: "Atom",
  vuejs: "Hexagon",
  svelte: "Flame",
  angular: "Shield",
  solidjs: "Diamond",
  nextjs: "Triangle",
  nuxt: "Hexagon",
  sveltekit: "Flame",
  astro: "Star",
  remix: "Repeat",
  nodejs: "Hexagon",
  bun: "Zap",
  deno: "Dinosaur",
  go: "Code2",
  rust: "Cog",
  python: "Code",
  elixir: "Droplet",
  supabase: "Database",
  convex: "Zap",
  planetscale: "Globe",
  neon: "Zap",
  turso: "Database",
  mongodb: "Leaf",
  upstash: "Cloud",
  clerk: "UserCheck",
  auth0: "Lock",
  nextauth: "Key",
  "supabase-auth": "ShieldCheck",
  "firebase-auth": "Flame",
  vercel: "Triangle",
  railway: "Train",
  netlify: "Globe",
  flyio: "Plane",
  render: "Cloud",
  "cloudflare-workers": "Cloud",
  liveblocks: "Users",
  pusher: "Radio",
  ably: "Wifi",
  socketio: "Plug",
  "claude-sonnet": "Brain",
  "gpt-4o": "MessageSquare",
  "gemini-pro": "Sparkles",
  "deepseek-v3": "Search",
  llama: "Bot",
  mistral: "Wind",
  tailwindcss: "Palette",
  shadcn: "Component",
  radix: "Blocks",
  mui: "Layers",
  vitest: "TestTube",
  playwright: "Play",
  cypress: "CheckCircle",
  sentry: "AlertTriangle",
  posthog: "BarChart3",
  mixpanel: "Activity",
  datadog: "Monitor",
  bolt: "Zap",
  lovable: "Heart",
  v0: "Code",
  replit: "Terminal",
  stackblitz: "Zap",
  "claude-code": "Terminal",
  "codex-cli": "Terminal",
  aider: "Bot",
  "continue-dev": "Play",
};

export const CATEGORY_ICONS: Record<string, string> = {
  ides: "Monitor",
  "ai-assistants": "Bot",
  frontend: "Layout",
  "meta-frameworks": "Layers",
  backend: "Server",
  databases: "Database",
  auth: "Lock",
  hosting: "Cloud",
  realtime: "Zap",
  llms: "Brain",
  styling: "Palette",
  testing: "FlaskConical",
  observability: "BarChart3",
  "vibe-coding": "Sparkles",
  "cli-agents": "Terminal",
};

interface DynamicIconProps extends Omit<LucideProps, "ref"> {
  name: string;
}

export function DynamicIcon({ name, ...props }: DynamicIconProps) {
  const IconComponent = iconComponents[name];
  
  if (!IconComponent) {
    return <HelpCircle {...props} />;
  }
  
  return <IconComponent {...props} />;
}

interface ToolIconProps extends Omit<LucideProps, "ref"> {
  toolSlug: string;
  fallback?: string;
}

export function ToolIcon({ toolSlug, fallback = "Package", ...props }: ToolIconProps) {
  const iconName = TOOL_ICONS[toolSlug] || fallback;
  return <DynamicIcon name={iconName} {...props} />;
}

interface CategoryIconProps extends Omit<LucideProps, "ref"> {
  categorySlug: string;
  fallback?: string;
}

export function CategoryIcon({ categorySlug, fallback = "Package", ...props }: CategoryIconProps) {
  const iconName = CATEGORY_ICONS[categorySlug] || fallback;
  return <DynamicIcon name={iconName} {...props} />;
}
