import { ConvexHttpClient } from "convex/browser";
import { api } from "../convex/_generated/api";

const client = new ConvexHttpClient(process.env.CONVEX_URL!);

type PricingModel = "free" | "freemium" | "paid" | "open_source" | "enterprise";

interface ToolData {
  name: string;
  slug: string;
  tagline: string;
  description: string;
  websiteUrl: string;
  githubUrl?: string;
  docsUrl?: string;
  categorySlug: string;
  pricingModel: PricingModel;
  githubStars?: number;
  pros: string[];
  cons: string[];
  bestFor: string[];
  features: string[];
  tags: string[];
  isOpenSource: boolean;
}

const mcpServerTools: ToolData[] = [
  {
    name: "Playwright MCP",
    slug: "playwright-mcp",
    tagline: "Official Microsoft Playwright MCP server for browser automation",
    description: "Official Microsoft Playwright MCP server, enabling LLMs to interact with web pages through structured accessibility snapshots. Provides browser automation for web scraping, testing, and interaction.",
    websiteUrl: "https://github.com/microsoft/playwright-mcp",
    githubUrl: "https://github.com/microsoft/playwright-mcp",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["Official Microsoft support", "Structured accessibility data", "Cross-browser support"],
    cons: ["Requires browser installation", "Resource intensive"],
    bestFor: ["Browser automation", "Web scraping", "E2E testing"],
    features: ["Browser control", "Accessibility snapshots", "Screenshot capture", "Form automation"],
    tags: ["browser", "automation", "playwright", "microsoft", "mcp"],
    isOpenSource: true,
  },
  {
    name: "Browser MCP",
    slug: "browser-mcp",
    tagline: "Automate your local Chrome browser with AI",
    description: "MCP server that enables AI assistants to automate your local Chrome browser. Provides tools for navigation, clicking, typing, and extracting data from web pages.",
    websiteUrl: "https://github.com/browsermcp/mcp",
    githubUrl: "https://github.com/browsermcp/mcp",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["Easy local setup", "Chrome integration", "Real browser automation"],
    cons: ["Chrome only", "Local execution required"],
    bestFor: ["Local browser automation", "Web testing", "Data extraction"],
    features: ["Chrome automation", "Page navigation", "Element interaction", "Data extraction"],
    tags: ["browser", "chrome", "automation", "mcp"],
    isOpenSource: true,
  },
  {
    name: "Puppeteer MCP",
    slug: "puppeteer-mcp",
    tagline: "Browser automation for web scraping and interaction",
    description: "MCP server using Puppeteer for browser automation. Enables web scraping, screenshot capture, and automated web interactions through AI assistants.",
    websiteUrl: "https://github.com/modelcontextprotocol/servers-archived/tree/main/src/puppeteer",
    githubUrl: "https://github.com/modelcontextprotocol/servers-archived",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["Headless browser support", "Screenshot capabilities", "PDF generation"],
    cons: ["Archived repository", "May need maintenance"],
    bestFor: ["Web scraping", "Screenshot automation", "PDF generation"],
    features: ["Headless browsing", "Screenshots", "PDF export", "Form filling"],
    tags: ["puppeteer", "browser", "scraping", "mcp"],
    isOpenSource: true,
  },
  {
    name: "Exa MCP Server",
    slug: "exa-mcp-server",
    tagline: "AI-powered web search through Exa API",
    description: "MCP server that provides AI-powered web search capabilities through the Exa API. Enables semantic search and content retrieval for AI assistants.",
    websiteUrl: "https://github.com/exa-labs/exa-mcp-server",
    githubUrl: "https://github.com/exa-labs/exa-mcp-server",
    categorySlug: "mcp-servers",
    pricingModel: "freemium",
    pros: ["Semantic search", "High-quality results", "AI-optimized"],
    cons: ["Requires API key", "Usage limits on free tier"],
    bestFor: ["Web research", "Content discovery", "AI-powered search"],
    features: ["Semantic search", "Content extraction", "Real-time results", "API integration"],
    tags: ["search", "exa", "semantic", "mcp", "research"],
    isOpenSource: true,
  },
  {
    name: "PostgreSQL MCP",
    slug: "postgres-mcp",
    tagline: "All-in-one MCP server for Postgres development and operations",
    description: "Comprehensive MCP server for PostgreSQL providing tools for performance analysis, tuning, health checks, and database operations through AI assistants.",
    websiteUrl: "https://github.com/crystaldba/postgres-mcp",
    githubUrl: "https://github.com/crystaldba/postgres-mcp",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["Performance analysis", "Health monitoring", "Query optimization"],
    cons: ["PostgreSQL only", "Requires database access"],
    bestFor: ["Database management", "Performance tuning", "Query optimization"],
    features: ["Schema inspection", "Query execution", "Performance analysis", "Health checks"],
    tags: ["postgres", "database", "sql", "mcp"],
    isOpenSource: true,
  },
  {
    name: "Supabase MCP",
    slug: "supabase-mcp-server",
    tagline: "Supabase integration with SQL execution and database exploration",
    description: "MCP server for Supabase providing SQL query execution, database exploration tools, and seamless integration with Supabase projects.",
    websiteUrl: "https://github.com/alexander-zuev/supabase-mcp-server",
    githubUrl: "https://github.com/alexander-zuev/supabase-mcp-server",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["Supabase integration", "SQL execution", "Schema exploration"],
    cons: ["Supabase specific", "Requires project access"],
    bestFor: ["Supabase projects", "Database queries", "Schema management"],
    features: ["SQL execution", "Schema inspection", "Table management", "Query building"],
    tags: ["supabase", "database", "sql", "mcp"],
    isOpenSource: true,
  },
  {
    name: "ClickHouse MCP",
    slug: "clickhouse-mcp",
    tagline: "ClickHouse database integration with schema inspection",
    description: "Official ClickHouse MCP server providing database integration with schema inspection and query capabilities for analytics workloads.",
    websiteUrl: "https://github.com/ClickHouse/mcp-clickhouse",
    githubUrl: "https://github.com/ClickHouse/mcp-clickhouse",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["Official support", "Analytics optimized", "Fast queries"],
    cons: ["ClickHouse specific", "Learning curve"],
    bestFor: ["Analytics", "OLAP workloads", "Large datasets"],
    features: ["Schema inspection", "Query execution", "Analytics support", "Performance optimization"],
    tags: ["clickhouse", "analytics", "database", "mcp"],
    isOpenSource: true,
  },
  {
    name: "Chroma MCP",
    slug: "chroma-mcp",
    tagline: "Vector database integration for RAG and embeddings",
    description: "Official Chroma MCP server for accessing local and cloud Chroma instances. Provides retrieval capabilities for RAG applications and embedding storage.",
    websiteUrl: "https://github.com/chroma-core/chroma-mcp",
    githubUrl: "https://github.com/chroma-core/chroma-mcp",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["Official support", "RAG optimized", "Local and cloud"],
    cons: ["Vector DB specific", "Requires embeddings knowledge"],
    bestFor: ["RAG applications", "Semantic search", "Embedding storage"],
    features: ["Vector storage", "Similarity search", "Collection management", "Embedding retrieval"],
    tags: ["chroma", "vector", "embeddings", "rag", "mcp"],
    isOpenSource: true,
  },
  {
    name: "Airtable MCP",
    slug: "airtable-mcp-server",
    tagline: "Read and write access to Airtable databases",
    description: "MCP server providing read and write access to Airtable databases with schema inspection and comprehensive CRUD capabilities.",
    websiteUrl: "https://github.com/domdomegg/airtable-mcp-server",
    githubUrl: "https://github.com/domdomegg/airtable-mcp-server",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["Full CRUD support", "Schema inspection", "Easy integration"],
    cons: ["Requires Airtable API key", "Rate limits apply"],
    bestFor: ["Airtable automation", "Data management", "No-code backends"],
    features: ["Read/write access", "Schema inspection", "Record management", "Base navigation"],
    tags: ["airtable", "database", "no-code", "mcp"],
    isOpenSource: true,
  },
  {
    name: "GitHub MCP",
    slug: "github-mcp-server",
    tagline: "GitHub integration for repository management",
    description: "MCP server for GitHub providing repository management, issue tracking, pull request handling, and code search capabilities.",
    websiteUrl: "https://github.com/modelcontextprotocol/servers",
    githubUrl: "https://github.com/modelcontextprotocol/servers",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["Official MCP server", "Comprehensive GitHub API", "Well maintained"],
    cons: ["Requires GitHub token", "API rate limits"],
    bestFor: ["Repository management", "Issue tracking", "Code review"],
    features: ["Repo management", "Issue tracking", "PR handling", "Code search"],
    tags: ["github", "git", "version-control", "mcp"],
    isOpenSource: true,
  },
  {
    name: "Slack MCP",
    slug: "slack-mcp-server",
    tagline: "Slack workspace integration for messaging and channels",
    description: "MCP server for Slack enabling AI assistants to interact with Slack workspaces, send messages, manage channels, and search conversations.",
    websiteUrl: "https://github.com/modelcontextprotocol/servers",
    githubUrl: "https://github.com/modelcontextprotocol/servers",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["Official MCP server", "Full Slack API access", "Channel management"],
    cons: ["Requires Slack app setup", "Workspace permissions needed"],
    bestFor: ["Team communication", "Message automation", "Channel management"],
    features: ["Message sending", "Channel management", "Search", "User lookup"],
    tags: ["slack", "messaging", "communication", "mcp"],
    isOpenSource: true,
  },
  {
    name: "Filesystem MCP",
    slug: "filesystem-mcp-server",
    tagline: "Secure file system access with configurable permissions",
    description: "MCP server providing secure file system access with configurable permissions. Enables reading, writing, and managing files through AI assistants.",
    websiteUrl: "https://github.com/modelcontextprotocol/servers",
    githubUrl: "https://github.com/modelcontextprotocol/servers",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["Secure access", "Configurable permissions", "Official support"],
    cons: ["Security considerations", "Local only"],
    bestFor: ["File management", "Code editing", "Document processing"],
    features: ["File read/write", "Directory listing", "Permission control", "Path navigation"],
    tags: ["filesystem", "files", "storage", "mcp"],
    isOpenSource: true,
  },
  {
    name: "Memory MCP",
    slug: "memory-mcp-server",
    tagline: "Persistent memory and knowledge graph for AI assistants",
    description: "MCP server providing persistent memory capabilities through a knowledge graph. Enables AI assistants to remember context across conversations.",
    websiteUrl: "https://github.com/modelcontextprotocol/servers",
    githubUrl: "https://github.com/modelcontextprotocol/servers",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["Persistent memory", "Knowledge graph", "Context retention"],
    cons: ["Storage requirements", "Graph complexity"],
    bestFor: ["Long-term memory", "Context management", "Knowledge storage"],
    features: ["Entity storage", "Relationship tracking", "Memory retrieval", "Context persistence"],
    tags: ["memory", "knowledge-graph", "context", "mcp"],
    isOpenSource: true,
  },
  {
    name: "Fetch MCP",
    slug: "fetch-mcp-server",
    tagline: "Web content fetching and extraction for AI",
    description: "MCP server for fetching and extracting web content in AI-friendly formats. Converts web pages to markdown for easy processing.",
    websiteUrl: "https://github.com/modelcontextprotocol/servers",
    githubUrl: "https://github.com/modelcontextprotocol/servers",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["Markdown conversion", "Clean extraction", "Official support"],
    cons: ["JavaScript rendering limited", "Rate limiting needed"],
    bestFor: ["Web scraping", "Content extraction", "Research"],
    features: ["URL fetching", "Markdown conversion", "Content extraction", "HTML parsing"],
    tags: ["fetch", "web", "scraping", "mcp"],
    isOpenSource: true,
  },
  {
    name: "Brave Search MCP",
    slug: "brave-search-mcp",
    tagline: "Web search through Brave Search API",
    description: "MCP server providing web search capabilities through the Brave Search API. Enables AI assistants to search the web with privacy-focused results.",
    websiteUrl: "https://github.com/modelcontextprotocol/servers",
    githubUrl: "https://github.com/modelcontextprotocol/servers",
    categorySlug: "mcp-servers",
    pricingModel: "freemium",
    pros: ["Privacy-focused", "Quality results", "Official support"],
    cons: ["API key required", "Usage limits"],
    bestFor: ["Web search", "Research", "Information retrieval"],
    features: ["Web search", "News search", "Image search", "Privacy protection"],
    tags: ["brave", "search", "privacy", "mcp"],
    isOpenSource: true,
  },
  {
    name: "Notion MCP",
    slug: "notion-mcp-server",
    tagline: "Notion workspace integration for pages and databases",
    description: "MCP server for Notion enabling AI assistants to interact with Notion workspaces, manage pages, query databases, and organize content.",
    websiteUrl: "https://github.com/modelcontextprotocol/servers",
    githubUrl: "https://github.com/modelcontextprotocol/servers",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["Full Notion API", "Database queries", "Page management"],
    cons: ["Notion API limits", "Complex permissions"],
    bestFor: ["Knowledge management", "Documentation", "Project tracking"],
    features: ["Page creation", "Database queries", "Block management", "Search"],
    tags: ["notion", "productivity", "documentation", "mcp"],
    isOpenSource: true,
  },
  {
    name: "Linear MCP",
    slug: "linear-mcp-server",
    tagline: "Linear issue tracking integration",
    description: "MCP server for Linear providing issue tracking, project management, and team collaboration capabilities through AI assistants.",
    websiteUrl: "https://github.com/jerhadf/linear-mcp-server",
    githubUrl: "https://github.com/jerhadf/linear-mcp-server",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["Full Linear API", "Issue management", "Project tracking"],
    cons: ["Linear subscription required", "API rate limits"],
    bestFor: ["Issue tracking", "Sprint planning", "Team collaboration"],
    features: ["Issue creation", "Project management", "Team sync", "Workflow automation"],
    tags: ["linear", "issues", "project-management", "mcp"],
    isOpenSource: true,
  },
  {
    name: "Sentry MCP",
    slug: "sentry-mcp-server",
    tagline: "Sentry error tracking integration",
    description: "MCP server for Sentry enabling AI assistants to query errors, analyze issues, and help debug applications through error tracking data.",
    websiteUrl: "https://github.com/modelcontextprotocol/servers",
    githubUrl: "https://github.com/modelcontextprotocol/servers",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["Error analysis", "Issue tracking", "Debug assistance"],
    cons: ["Sentry account required", "Data access permissions"],
    bestFor: ["Error debugging", "Issue triage", "Performance monitoring"],
    features: ["Error queries", "Issue analysis", "Stack traces", "Performance data"],
    tags: ["sentry", "errors", "debugging", "monitoring", "mcp"],
    isOpenSource: true,
  },
  {
    name: "Cloudflare MCP",
    slug: "cloudflare-mcp-server",
    tagline: "Cloudflare services integration",
    description: "MCP server for Cloudflare enabling management of Workers, KV, R2, and other Cloudflare services through AI assistants.",
    websiteUrl: "https://github.com/cloudflare/mcp-server-cloudflare",
    githubUrl: "https://github.com/cloudflare/mcp-server-cloudflare",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["Official Cloudflare support", "Full API access", "Edge computing"],
    cons: ["Cloudflare account required", "Complex permissions"],
    bestFor: ["Edge deployment", "CDN management", "Serverless functions"],
    features: ["Workers management", "KV storage", "R2 buckets", "DNS management"],
    tags: ["cloudflare", "edge", "cdn", "workers", "mcp"],
    isOpenSource: true,
  },
  {
    name: "AWS CDK MCP",
    slug: "aws-cdk-mcp",
    tagline: "AWS CDK advice and infrastructure patterns",
    description: "MCP server providing prescriptive CDK advice, CDK Nag rule explanations, and AWS Solutions Constructs patterns for infrastructure as code.",
    websiteUrl: "https://github.com/awslabs/mcp/tree/main/src/cdk-mcp-server",
    githubUrl: "https://github.com/awslabs/mcp",
    categorySlug: "mcp-servers",
    pricingModel: "open_source",
    pros: ["AWS official", "Best practices", "Pattern library"],
    cons: ["AWS specific", "CDK knowledge required"],
    bestFor: ["Infrastructure as code", "AWS deployment", "Cloud architecture"],
    features: ["CDK guidance", "Nag rules", "Construct patterns", "Schema generation"],
    tags: ["aws", "cdk", "infrastructure", "cloud", "mcp"],
    isOpenSource: true,
  },
];

const claudePluginTools: ToolData[] = [
  {
    name: "Claude Task Master",
    slug: "claude-task-master",
    tagline: "AI-powered task management and project planning for Claude",
    description: "Comprehensive task management system for Claude Code featuring AI-powered task breakdown, dependency tracking, and project planning capabilities.",
    websiteUrl: "https://github.com/eyaltoledano/claude-task-master",
    githubUrl: "https://github.com/eyaltoledano/claude-task-master",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["AI task breakdown", "Dependency tracking", "Project planning"],
    cons: ["Learning curve", "Setup required"],
    bestFor: ["Project management", "Task planning", "Development workflows"],
    features: ["Task breakdown", "Dependencies", "Progress tracking", "AI planning"],
    tags: ["tasks", "planning", "project-management", "claude"],
    isOpenSource: true,
  },
  {
    name: "Superpowers",
    slug: "superpowers-claude",
    tagline: "Core skills library with 20+ battle-tested Claude Code skills",
    description: "Comprehensive skills library for Claude Code featuring TDD, debugging, collaboration patterns, brainstorming, and plan execution commands.",
    websiteUrl: "https://github.com/obra/superpowers",
    githubUrl: "https://github.com/obra/superpowers",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["Battle-tested skills", "TDD support", "Collaboration patterns"],
    cons: ["Plugin system knowledge needed", "Configuration required"],
    bestFor: ["Development workflows", "TDD", "Debugging"],
    features: ["Brainstorm command", "Plan execution", "Skills search", "Debugging tools"],
    tags: ["skills", "tdd", "debugging", "claude", "workflow"],
    isOpenSource: true,
  },
  {
    name: "Repomix",
    slug: "repomix",
    tagline: "Pack your codebase for LLM context",
    description: "Tool for packing your entire codebase into AI-friendly formats. Perfect for feeding codebases to Claude, ChatGPT, and other LLMs.",
    websiteUrl: "https://github.com/yamadashy/repomix",
    githubUrl: "https://github.com/yamadashy/repomix",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["Easy codebase packing", "Multiple output formats", "Customizable"],
    cons: ["Large repos may exceed context", "Manual execution"],
    bestFor: ["Code context", "LLM input preparation", "Repository analysis"],
    features: ["Codebase packing", "Format options", "Ignore patterns", "Token counting"],
    tags: ["codebase", "context", "llm", "packing", "claude"],
    isOpenSource: true,
  },
  {
    name: "Claude Flow",
    slug: "claude-flow",
    tagline: "Multi-agent orchestration platform for Claude",
    description: "Leading agent orchestration platform for Claude. Deploy intelligent multi-agent swarms and coordinate autonomous workflows.",
    websiteUrl: "https://github.com/ruvnet/claude-flow",
    githubUrl: "https://github.com/ruvnet/claude-flow",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["Multi-agent support", "Swarm coordination", "Autonomous workflows"],
    cons: ["Complex setup", "Resource intensive"],
    bestFor: ["Multi-agent systems", "Complex workflows", "Autonomous tasks"],
    features: ["Agent orchestration", "Swarm deployment", "Workflow coordination", "Task distribution"],
    tags: ["agents", "orchestration", "swarm", "claude", "automation"],
    isOpenSource: true,
  },
  {
    name: "Claude Mem",
    slug: "claude-mem",
    tagline: "Persistent memory system for Claude Code",
    description: "Memory management system for Claude Code enabling persistent context, session continuity, and knowledge retention across conversations.",
    websiteUrl: "https://github.com/thedotmack/claude-mem",
    githubUrl: "https://github.com/thedotmack/claude-mem",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["Persistent memory", "Session continuity", "Context retention"],
    cons: ["Storage management", "Memory limits"],
    bestFor: ["Long projects", "Context preservation", "Knowledge management"],
    features: ["Memory storage", "Context retrieval", "Session management", "Knowledge persistence"],
    tags: ["memory", "context", "persistence", "claude"],
    isOpenSource: true,
  },
  {
    name: "Playwright Skill",
    slug: "playwright-skill",
    tagline: "Playwright browser automation skill for Claude",
    description: "Claude Code skill for browser automation using Playwright. Enables web testing, UI verification, and automated browser interactions.",
    websiteUrl: "https://github.com/lackeyjb/playwright-skill",
    githubUrl: "https://github.com/lackeyjb/playwright-skill",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["Browser automation", "Test integration", "UI verification"],
    cons: ["Playwright setup required", "Browser dependencies"],
    bestFor: ["Web testing", "UI automation", "E2E testing"],
    features: ["Browser control", "Test execution", "Screenshot capture", "Form automation"],
    tags: ["playwright", "testing", "browser", "automation", "claude"],
    isOpenSource: true,
  },
  {
    name: "Claude Scientific Skills",
    slug: "claude-scientific-skills",
    tagline: "Scientific research and analysis skills for Claude",
    description: "Collection of Claude Code skills for scientific research, data analysis, and academic writing assistance.",
    websiteUrl: "https://github.com/K-Dense-AI/claude-scientific-skills",
    githubUrl: "https://github.com/K-Dense-AI/claude-scientific-skills",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["Research focused", "Data analysis", "Academic writing"],
    cons: ["Specialized use case", "Domain knowledge helpful"],
    bestFor: ["Scientific research", "Data analysis", "Academic work"],
    features: ["Research tools", "Data analysis", "Citation management", "Writing assistance"],
    tags: ["science", "research", "analysis", "academic", "claude"],
    isOpenSource: true,
  },
  {
    name: "Claude Code Templates",
    slug: "claude-code-templates",
    tagline: "Collection of templates and resources for Claude Code",
    description: "Comprehensive collection of templates, slash commands, hooks, and agents for Claude Code workflows with usage dashboard and analytics.",
    websiteUrl: "https://github.com/davila7/claude-code-templates",
    githubUrl: "https://github.com/davila7/claude-code-templates",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["Comprehensive templates", "Usage analytics", "Well organized"],
    cons: ["Template customization needed", "Learning curve"],
    bestFor: ["Quick start", "Workflow templates", "Best practices"],
    features: ["Slash commands", "Hooks", "Agents", "Analytics dashboard"],
    tags: ["templates", "commands", "hooks", "agents", "claude"],
    isOpenSource: true,
  },
  {
    name: "Claude Code Tools",
    slug: "claude-code-tools",
    tagline: "Session continuity and cross-agent handoff tools",
    description: "Toolset for session continuity featuring skills to avoid compaction, recover context across sessions, and enable cross-agent handoff between Claude Code and Codex CLI.",
    websiteUrl: "https://github.com/pchalasani/claude-code-tools",
    githubUrl: "https://github.com/pchalasani/claude-code-tools",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["Session continuity", "Cross-agent handoff", "Context recovery"],
    cons: ["Setup complexity", "Multiple tool integration"],
    bestFor: ["Long sessions", "Multi-agent workflows", "Context preservation"],
    features: ["Session search", "Context recovery", "Agent handoff", "Safety hooks"],
    tags: ["session", "continuity", "handoff", "context", "claude"],
    isOpenSource: true,
  },
  {
    name: "ClaudeKit",
    slug: "claudekit",
    tagline: "CLI toolkit with auto-save and specialized subagents",
    description: "Impressive CLI toolkit providing auto-save checkpointing, code quality hooks, specification generation, and 20+ specialized subagents for Claude Code workflows.",
    websiteUrl: "https://github.com/carlrannaberg/claudekit",
    githubUrl: "https://github.com/carlrannaberg/claudekit",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["Auto-save checkpoints", "Specialized subagents", "Code quality hooks"],
    cons: ["CLI focused", "Configuration needed"],
    bestFor: ["Development workflows", "Code quality", "Automated checkpoints"],
    features: ["Auto-save", "Subagents", "Code review", "Spec generation"],
    tags: ["cli", "toolkit", "subagents", "checkpoints", "claude"],
    isOpenSource: true,
  },
  {
    name: "Ultrathink",
    slug: "ultrathink-claude",
    tagline: "Enhanced thinking and reasoning plugin for Claude",
    description: "Plugin that enhances Claude's thinking and reasoning capabilities with structured problem-solving approaches and deep analysis tools.",
    websiteUrl: "https://github.com/ccplugins/awesome-claude-code-plugins",
    githubUrl: "https://github.com/ccplugins/awesome-claude-code-plugins",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["Enhanced reasoning", "Structured thinking", "Deep analysis"],
    cons: ["Token intensive", "Complex problems only"],
    bestFor: ["Complex problems", "Deep analysis", "Strategic thinking"],
    features: ["Extended thinking", "Problem decomposition", "Analysis tools", "Reasoning chains"],
    tags: ["thinking", "reasoning", "analysis", "claude"],
    isOpenSource: true,
  },
  {
    name: "PR Review Toolkit",
    slug: "pr-review-toolkit",
    tagline: "Automated PR review and code analysis for Claude",
    description: "Official Claude Code plugin for automated pull request review, code analysis, and quality feedback generation.",
    websiteUrl: "https://github.com/ccplugins/awesome-claude-code-plugins",
    githubUrl: "https://github.com/ccplugins/awesome-claude-code-plugins",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["Automated reviews", "Code analysis", "Quality feedback"],
    cons: ["GitHub integration required", "Review customization"],
    bestFor: ["Code review", "PR automation", "Quality assurance"],
    features: ["PR analysis", "Code suggestions", "Quality checks", "Feedback generation"],
    tags: ["pr", "review", "code-quality", "github", "claude"],
    isOpenSource: true,
  },
  {
    name: "Feature Dev",
    slug: "feature-dev-claude",
    tagline: "Feature development workflow plugin for Claude",
    description: "Official Claude Code plugin for structured feature development workflows including planning, implementation, and testing phases.",
    websiteUrl: "https://github.com/ccplugins/awesome-claude-code-plugins",
    githubUrl: "https://github.com/ccplugins/awesome-claude-code-plugins",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["Structured workflow", "End-to-end development", "Best practices"],
    cons: ["Workflow adherence required", "Learning curve"],
    bestFor: ["Feature development", "Structured coding", "Project workflows"],
    features: ["Planning phase", "Implementation", "Testing", "Documentation"],
    tags: ["feature", "development", "workflow", "claude"],
    isOpenSource: true,
  },
  {
    name: "Security Guidance",
    slug: "security-guidance-claude",
    tagline: "Security best practices and vulnerability detection",
    description: "Official Claude Code plugin providing security guidance, vulnerability detection, and secure coding best practices.",
    websiteUrl: "https://github.com/ccplugins/awesome-claude-code-plugins",
    githubUrl: "https://github.com/ccplugins/awesome-claude-code-plugins",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["Security focused", "Vulnerability detection", "Best practices"],
    cons: ["Security expertise helpful", "False positives possible"],
    bestFor: ["Security review", "Vulnerability scanning", "Secure coding"],
    features: ["Vulnerability detection", "Security analysis", "Best practices", "Remediation guidance"],
    tags: ["security", "vulnerabilities", "best-practices", "claude"],
    isOpenSource: true,
  },
  {
    name: "DevOps Automator",
    slug: "devops-automator-claude",
    tagline: "DevOps automation and infrastructure management",
    description: "Claude Code plugin for DevOps automation including CI/CD pipelines, infrastructure management, and deployment workflows.",
    websiteUrl: "https://github.com/ccplugins/awesome-claude-code-plugins",
    githubUrl: "https://github.com/ccplugins/awesome-claude-code-plugins",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["DevOps automation", "CI/CD support", "Infrastructure management"],
    cons: ["DevOps knowledge required", "Platform specific"],
    bestFor: ["DevOps workflows", "CI/CD", "Infrastructure automation"],
    features: ["Pipeline automation", "Infrastructure management", "Deployment", "Monitoring"],
    tags: ["devops", "automation", "cicd", "infrastructure", "claude"],
    isOpenSource: true,
  },
  {
    name: "N8N Workflow Builder",
    slug: "n8n-workflow-builder",
    tagline: "N8N workflow creation and automation",
    description: "Claude Code plugin for building and managing N8N automation workflows through natural language instructions.",
    websiteUrl: "https://github.com/ccplugins/awesome-claude-code-plugins",
    githubUrl: "https://github.com/ccplugins/awesome-claude-code-plugins",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["N8N integration", "Natural language", "Workflow automation"],
    cons: ["N8N knowledge helpful", "Workflow complexity"],
    bestFor: ["Workflow automation", "N8N users", "Integration building"],
    features: ["Workflow creation", "Node configuration", "Automation", "Integration"],
    tags: ["n8n", "workflow", "automation", "integration", "claude"],
    isOpenSource: true,
  },
  {
    name: "iOS Simulator Skill",
    slug: "ios-simulator-skill",
    tagline: "iOS Simulator control and testing for Claude",
    description: "Claude Code skill for controlling iOS Simulator, enabling mobile app testing and UI automation on macOS.",
    websiteUrl: "https://github.com/conorluddy/ios-simulator-skill",
    githubUrl: "https://github.com/conorluddy/ios-simulator-skill",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["iOS testing", "Simulator control", "UI automation"],
    cons: ["macOS only", "Xcode required"],
    bestFor: ["iOS development", "Mobile testing", "UI automation"],
    features: ["Simulator control", "App testing", "Screenshot capture", "UI interaction"],
    tags: ["ios", "simulator", "testing", "mobile", "claude"],
    isOpenSource: true,
  },
  {
    name: "Serena",
    slug: "serena-coding-agent",
    tagline: "Fully-featured coding agent with language server support",
    description: "A fully-featured coding agent that relies on symbolic code operations using language servers for precise code understanding and manipulation.",
    websiteUrl: "https://github.com/oraios/serena",
    githubUrl: "https://github.com/oraios/serena",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["Language server integration", "Symbolic operations", "Precise code handling"],
    cons: ["LSP setup required", "Language specific"],
    bestFor: ["Code refactoring", "Precise edits", "Multi-language projects"],
    features: ["LSP integration", "Code navigation", "Refactoring", "Symbol analysis"],
    tags: ["coding-agent", "lsp", "refactoring", "claude"],
    isOpenSource: true,
  },
  {
    name: "Container Use",
    slug: "container-use",
    tagline: "Development environments for coding agents",
    description: "Development environments enabling multiple agents to work safely and independently with your preferred stack in isolated containers.",
    websiteUrl: "https://github.com/dagger/container-use",
    githubUrl: "https://github.com/dagger/container-use",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["Isolated environments", "Multi-agent support", "Safe execution"],
    cons: ["Docker required", "Resource overhead"],
    bestFor: ["Multi-agent development", "Safe code execution", "Isolated testing"],
    features: ["Container isolation", "Multi-agent support", "Stack configuration", "Safe execution"],
    tags: ["containers", "docker", "isolation", "agents", "claude"],
    isOpenSource: true,
  },
  {
    name: "Skill Seekers",
    slug: "skill-seekers",
    tagline: "Convert documentation websites into Claude Skills",
    description: "Tool for converting documentation websites into Claude Skills, enabling AI assistants to access and use documentation as skills.",
    websiteUrl: "https://github.com/yusufkaraaslan/Skill_Seekers",
    githubUrl: "https://github.com/yusufkaraaslan/Skill_Seekers",
    categorySlug: "claude-plugins",
    pricingModel: "open_source",
    pros: ["Documentation conversion", "Skill generation", "Easy integration"],
    cons: ["Documentation quality dependent", "Processing time"],
    bestFor: ["Documentation access", "Skill creation", "Knowledge integration"],
    features: ["Doc scraping", "Skill generation", "Format conversion", "Integration"],
    tags: ["documentation", "skills", "conversion", "claude"],
    isOpenSource: true,
  },
];

async function ingestTools() {
  console.log("Starting tool ingestion from awesome-* repos...\n");

  const allTools = [...mcpServerTools, ...claudePluginTools];
  let created = 0;
  let updated = 0;
  let errors: string[] = [];

  for (const tool of allTools) {
    try {
      const result = await client.mutation(api.ingest.upsertTool, tool);
      if (result.action === "created") {
        created++;
        console.log(`Created: ${tool.name} (${tool.categorySlug})`);
      } else {
        updated++;
        console.log(`Updated: ${tool.name} (${tool.categorySlug})`);
      }
    } catch (error) {
      const errorMsg = `Error ingesting ${tool.name}: ${error}`;
      errors.push(errorMsg);
      console.error(errorMsg);
    }
  }

  console.log("\n=== Ingestion Complete ===");
  console.log(`Created: ${created}`);
  console.log(`Updated: ${updated}`);
  console.log(`Errors: ${errors.length}`);
  if (errors.length > 0) {
    console.log("\nErrors:");
    errors.forEach((e) => console.log(`  - ${e}`));
  }
}

ingestTools().catch(console.error);
